### ISSUE TITLE
Add Placeholder Content to The `Conversion Tracking ID` Field (`AW-`)

### ISSUE THREAD

**Issue by 10upsimon** [google/site-kit-wp#8398]
## Feature Description

As part of a stint of recently identified Ads Module Phase 1 updates is the need to create placeholder text for the `Conversion Tracking ID` field, so that it is clear that users should enter only the numerical aspect of the gtag ID, and not the `AW-` portion.

This will take the form of a pre-applied `AW-` placeholder within the input field, as per the following Figma mock:

<img width="1577" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlRkQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--06dfa7e9660d613ee9e8faf81be3197f2d912d1a/image.png" alt="image.png" />

The Figma mock can be found [here](https://www.figma.com/file/THG1FJw5SaUxmiq38Mkf1x/Ads?type=design&node-id=653-3876&mode=design&t=EATE08eXwZ3T9n5J-0).

These updates will apply to the input field currently found within the `SetupComponent` and `SettingsEdit` components of the Ads Module.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The input fields for  the `Conversion Tracking ID` field, found within the `SetupComponent` and `SettingsEdit` components of the Ads Module, should meet the following criteria:
    * Permanent placeholder text should be present within the input field that prepends `AW-` to the value the user is entering.
    * The user should still be able to type or paste the full `AW-XXXXX` pattern of the ID, but it will be magically stripped away, indicating the full `AW-` field as a combination of the pre-existing `AW-` portion and the numerical part entered as part of the user input.
    * Field placeholder text following the permanent `AW-` text should read as per the Figma mock
    * Field validation messages should remain as they are.

## Implementation Brief

* [x] Update `assets/js/googlesitekit/components-gm2/TextField.js`
  * Include `leadingIcon` prop - it should accept type `element` (we can pass html markup or svg), and add it to the `MaterialTextField` component as `leadingIcon` prop
* [x] Update `assets/js/modules/ads/components/common/AdsConversionIDTextField.js`: 
  * Add `leadingIcon` prop to the `TextField` component, and pass `<span className="googlesitekit-text-field-conversion-tracking-id-prefix">__('AW-', 'google-site-kit')</span>` markup for example
  * Update the `value` prop to replace `AW` and `AW-` with empty string. Example `adsConversionID?.replace( 'AW-', '' )?.replace( 'AW', '' )`
* [x] Add `assets/sass/components/setup/_googlesitekit-ads-conversion-tracking-id.scss`
  * Apply the styling for `AW` prefix and main input value as per figma design 

### Test Coverage

* No test update is needed

## QA Brief

* Enable the Ads module
* Test the Conversion Tracking ID field works as in the AC for typed and copied and pasted IDs in both the setup and settings components.

## Changelog entry

* Add placeholder/prefix to the Conversion Tracking ID field in the Ads module.

**Comment by techanvil** [comment]
AC LGTM :white_check_mark:

Note that I've added #8251 as a dependency.

**Comment by mohitwp** [comment]
### QA Update ❌ 


- Tested on dev environment.
- Verified Ads conversion field as per AC.
- @benbowler Please find my observations below.


_1) Text 'Conversion Tracking ID' is not aligned with permanent placeholder text AW_

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/15d7cba2-ba9a-463c-97a7-747148c524ac)

</details>

_2) When I copy paste AW-123456 conversion id then (AW-) gets remove but when I type AW- then AW is getting remove but not -. Can we also remove - in case of typing ?_

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/e4025a25-f43f-42da-adf8-0aea1c413dde)

</details>

_3)Can we implement validation for the maximum number of digits allowed for the Conversion ID?_

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/cb09e265-24db-45b4-97de-66eda6739ef2)

![image](https://github.com/google/site-kit-wp/assets/94359491/a93733e5-0351-4839-8746-8d609b3819e8)

</details>

_Q-4) As per AC- Field validation messages should remain as they are. But currently validation messages are not same._

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/f5df19f4-cc08-4c8c-972b-045b2035d629)

![image](https://github.com/google/site-kit-wp/assets/94359491/3ac48300-a4c1-4e80-b3fd-deeaa0458d19)

</details>

**Comment by benbowler** [comment]
Hey @mohitwp, I addressed comments 1, 2 and 3. RE comment 4 the AC is out of date and we should use the field validation messages in the Figma mocks.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on main environment.
- Verified that issue reported[ above](https://github.com/google/site-kit-wp/issues/8398#issuecomment-2031656011) are now resolved.

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/c0b2359a-f756-4ae6-86ac-e4cade25727e)

![image](https://github.com/google/site-kit-wp/assets/94359491/b8d0b032-d506-4321-ad44-1ae45ff9294f)

![image](https://github.com/google/site-kit-wp/assets/94359491/8d4f1f5d-d8ee-4a4c-ba22-f268d4494dc2)


https://github.com/google/site-kit-wp/assets/94359491/1dfb1298-1415-42cb-b24a-1fb30c184ee9

</details>
