### ISSUE TITLE
Rename the "Ads Conversion ID" setting and selectors to "Conversion ID" (or "Conversion Tracking ID") in the Ads module

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#8473]
## Feature Description

Previously the "Ads Conversion ID" setting was stored in the Analytics module so had the `ads` prefix on it, but now that it's moved to the Ads module and is referenced in the UI as the "Conversion Tracking ID", we should update our settings variable names and our selectors to reference this value as the `conversionID` or `conversionTrackingID`, instead of `adsConversionID`.

The setting in question is here: https://github.com/google/site-kit-wp/blob/f62f92a654617fc1fa0b781b0e33f9c534fe335d/includes/Modules/Ads/Settings.php#L49

We can change these settings without bothering with a migration, given no users have interacted with this setting yet, as long as it's ready for the `1.125.0` release.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `adsConversionID` setting in the `Modules/Ads` code should be renamed to `conversionID`.
* All selectors/variables in JS that deal with `adsConversionID` to use `conversionID` without the `ads` prefix.
* No migration is needed because this functionality has no shipped to users in production, so a simple renaming is fine.

#### PHP Changes

* [x] In the `includes/Modules/Ads` directory, perform a case-sensitive and whole-word search for all instances of `adsConversionID` and replace them with `conversionID`.
* [x] In `includes/Modules/Ads.php`, locate the definition of the `adsConversionID` option and update it to `conversionID`.

#### JavaScript Changes

* [x] In the `./assets/js/modules/ads` directory, perform a case-sensitive and whole-word search for all instances of `adsConversionID` and replace them with `conversionID`.
* [x] Search for `getAdsConversionID` selectors and replace them with `getConversionID`.
* [x] In `assets/js/modules/ads/utils/validation.js`, rename the `isValidAdsConversionID` function to `isValidConversionID`.
* [x] Update the usages of `isValidAdsConversionID` to `isValidConversionID`.
* [x] Ensure the base settings datastore is updated to reflect the new setting name.
* [x] Ensure all usages of the setting, selector, and validation function are updated accordingly.

### Test Coverage

* [x] No new tests are required for the changes.
* [x] In `tests/phpunit/integration/Modules/Ads` and `tests/phpunit/integration/Modules/AdsTest.php`, ensure all the instances of `adsConversionID` are updated to `conversionID`.
* [x] In `./assets/js/modules/ads`, ensure all the instances of `adsConversionID` and `getAdsConversionID` are updated to `conversionID` and `getConversionID` respectively.

## QA Brief

* Set up the Ads module and run through usual Ads Module tests and ensure no regressions come from the change in setting name.

**Note to QA:** This change includes the renaming of the Conversion Tracking ID setting in the module code for the Ads module _without a migration because this change has not yet gone out to users_. This means that loading any _existing site with Site Kit installed and the Ads Module setup_ will now show the Ads module as being in an "incomplete setup" state.

This is expected behaviour because we didn't bother with a needless migration (because this has not gone out to users yet). So QA/testing needs to be done on a new Site Kit install or at least after resetting/removing the Ads Module from a site 🙂 

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by bethanylang** [comment]
@hussain-t Nevermind, Zenhub was being weird. I see it now!

**Comment by bethanylang** [comment]
Changed to a P0 since this needs to be completed in Sprint 125 to align with the Ads Module release.

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified Ad module set up on New site.
- Verified Ads module migration on new site.
- Not found any regression.

<details>


https://github.com/google/site-kit-wp/assets/94359491/39aedb48-c54d-4b4b-9273-e948819479c9


https://github.com/google/site-kit-wp/assets/94359491/2d0392ab-f271-461e-b0ed-4319e990a199

</details>

**Comment by aaemnnosttv** [comment]
## ❌ Approval

This has removed the "Ads" prefix from its debug (Site Health) fields where it should be kept for presentational purposes.

https://github.com/google/site-kit-wp/blob/ec3f4cfe6c25c2ea23fe714517861ea6e790e2ee/includes/Modules/Ads.php#L184-L185

This was correct previously so the change to the key and label just needs to be reverted while keeping the change to the setting key.

**Comment by aaemnnosttv** [comment]
Opened a quick PR to address the above ^

**Comment by nfmohit** [comment]
PR merged. This is now back in QA. Thanks @aaemnnosttv !

**Comment by aaemnnosttv** [comment]
This doesn't need to go through QA again but I've given it another quick test, thanks @nfmohit !
