### ISSUE TITLE
Ensure that Conversion Tracking ID is placed for AMP

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#8518]
## Bug Description

As reported by @wpdarren in [Ads Module Bug Bash](https://app.asana.com/0/1206715995671666/1207045250677122/f) and discussed in [Slack](https://10up.slack.com/archives/CBKKQEBR9/p1712757309242129), when a user has the AMP plugin installed, the Conversion Tracking ID from the Ads module should be placed in the AMP source code.

cc @10upsimon 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When using AMP, the Conversion Tracking ID setting obtained from the Ads Module should be output within the AMP source in the same manner that it is currently output by the GA4 module (as an AMP compatible gtag) if the legacy Ads Conversion ID field is being used.

## Implementation Brief

* [ ] Create a new class `AMP_Tag` in the `Ads` module in the file `includes/Modules/Ads/AMP_Tag.php` based on the same class [in the `Analytics_4` module](includes/Modules/Analytics_4/AMP_Tag.php).
   * [ ] Copy the `register` and `render` methods from the `AMP_Tag` class [the `Analytics_4` module](includes/Modules/Analytics_4/AMP_Tag.php).
* [ ] Within the `Ads` module, import the new AMP_Tag class `use Google\Site_Kit\Modules\Ads\AMP_Tag;`.
* [ ] Update the `register_tag` method in the `Ads` module:
   * [ ] Update the `$tag` variable to create a new AMP tag when in the AMP Context:
   ```
   $tag = $this->context->is_amp()
	? new AMP_Tag( $ads_conversion_id, self::MODULE_SLUG )
	: new Web_Tag( $ads_conversion_id, self::MODULE_SLUG );
   ```
    * [ ] Update the main `Ads` module class and set the home domain after `$tag` instantiation:
```
$home_domain = URL::parse( $this->context->get_canonical_home_url(), PHP_URL_HOST );
$tag->set_home_domain( $home_domain );
```

* [] Create new `Tag_With_Linker` interface inside of `Core/Tags` and require the following methods:
````
public function set_home_domain( $domain );
````
* [ ] This will require that the `set_home_domain` method be present, which is required for the trait logic below to function as intended.
* [ ] Create new `Tag_With_Linker_Trait` trait inside of `Core/Tags` and implement the following logic:
```
private $home_domain;

public function set_home_domain( $home_domain ) {
    $this->home_domain = $home_domain;
}

protected function add_linker_to_tag_config( $tag_config ) {
	return array_merge( $tag_config, array( 'linker' => array( 'domains' => array( $this->home_domain ) ) ) );
}
```
    * [ ] This trait will be used to set the domain, and to add the linker to tag configs within the `get_tag_config()` method of the tag classes using it
* [ ] Update both the `Ads` and `Analytics_4` amp tag classes to utilise the new interface and trait
    * [ ] Ensure that the `$config` array returned within the `get_tag_config()` method uses the `add_linker_to_tag_config` method to add in the linker, i.e
    ```
    return $this->add_linker_to_tag_config( $config );
    ```
* [ ] Update the `Analytics_4/Web_Tag` class to make use of the new `Tag_With_Linker_Interface` interface and `Tag_With_Linker_Trait` trait, including the use of the `add_linker_to_tag_config` method as indicated above
* [ ] Update the `Analytics_4/AMP_Tag` class to make use of the new `Tag_With_Linker_Interface` interface and `Tag_With_Linker_Trait` trait, including the use of the `add_linker_to_tag_config` method as indicated above
* [ ] Update the existing `Tag_Interface` interface and remove the requirement of the `set_home_domain` method, given that this now resides within the `Tag_With_Linker_Interface` interface

### Test Coverage

* Create a new test suite that covers the `Ads/AMP_Tag` logic to assert that the `<amp-analytics>` tag is present in the footer, with the correct tag ID and linker domain.

## QA Brief

* Set up and connect the Ads module using a mock Conversion ID, i.e `AW-12345`
* Ensure that the AMP plugin is installed and active
* Navigate to a page on the site and view it in AMP mode, i.e by appending `?amp=1` to a URL, or adding `/amp` to the URL
* Validate that the `<amp-analytics>` tag is present in the source code
* Validate that the contents of the tag (JSON object) contains the expected conversion ID (`AW-12345`) as the value of the `gtag_id` property, and that the tag ID following the `config` property is also equal to the same ID. An example tag output in source is shown below:
```
<amp-analytics type="gtag" data-credentials="include" class="i-amphtml-layout-fixed i-amphtml-layout-size-defined" style="width:1px;height:1px" i-amphtml-layout="fixed"><script type="application/json">{"optoutElementId":"__gaOptOutExtension","vars":{"gtag_id":"AW-12345","config":{"AW-12345":{"groups":"default"},"linker":{"domains":["sitekit.10uplabs.com"]}}}}</script></amp-analytics>
```
* Validate that the domains entry as seen in the tag source is equal to the domain of the test site in question
* Enable GA4
* Validate that the GA4 `<amp-analytics>` tag is output _in addition_ to the Ads one, the Ads one should _not_ be replaced with the GA4 one.

## Changelog entry

* Add AMP tag with Conversion Tracking ID when Ads module is enabled.

**Comment by tofumatt** [comment]
ACs 👍🏻

**Comment by eugene-manuilov** [comment]
IB ✔️, but i am going to reduce the estimate to 7 since this is more than enough for this task.

**Comment by 10upsimon** [comment]
Noting that after internal discussion with @eugene-manuilov the IB was amended accordingly to cater for the creation of a new `Tag_With_Linker_Interface` interface and a `Tag_With_Linker_Trait` trait, as the existing `Tag_Interface` was too stringent in it's implementation and would have resulted in the `Ads/AMP_Tag` class needing to implement unnecessary methods.

This will result in updates being needed to the `Analytics_4\Web_Tag`, `Analytics_4\AMP_Tag` and  `Ads\Web_Tag` classes, given the separation of concern here.

The existing `Tag_Interface` interface will also need to be updated to remove the requirement of the `set_home_domain` method, which is now present in the `Tag_With_Linker` interface.

cc @aaemnnosttv @zutigrm @benbowler

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on main environment.
- Verified that that the <amp-analytics> tag is present in the source code.
- Verified that the contents of the tag (JSON object) contains the expected conversion ID (AW-12345) as the value of the gtag_id property, and that the tag ID following the config property is also equal to the same ID. 
- 
- `<amp-analytics type="gtag" data-credentials="include" class="i-amphtml-layout-fixed i-amphtml-layout-size-defined" style="width:1px;height:1px" i-amphtml-layout="fixed"><script type="application/json">{"optoutElementId":"__gaOptOutExtension","vars":{"gtag_id":"AW-12345","config":{"AW-12345":{"groups":"default"},"linker":{"domains":["boundlessplace.s4-tastewp.com"]}}}}</script></amp-analytics>`
- 
- Verified that the domains entry as seen in the tag source is equal to the domain of the test site in question
- Verified that the if analytics is connected then GA4 <amp-analytics> tag is output in addition to the Ads one, the Ads one not be replaced with the GA4 one

<details>

Without GA4

![image](https://github.com/google/site-kit-wp/assets/94359491/3e5b94d7-cf7e-4e7f-ba32-2186060f9f32)

With Ga4

![image](https://github.com/google/site-kit-wp/assets/94359491/47139d46-54a7-44bd-b8e8-831773822233)

</details>
