### ISSUE TITLE
Implement partner service for conversion tracking

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8561]
## Feature Description

The partner conversion tracking service currently supports the following functions that are relevant for our use:

- [providing a list of supported conversion goal labels](https://github.com/google/partner-ads-experience/blob/e6f030b1b2ab8ed8936538181e414dc50df11a2b/sdk/service/partner/conversion-tracking-service.d.ts#L81-L88)
	- It is expected that this will be an empty list for now
- [providing data to support a page view conversion fallback](https://github.com/google/partner-ads-experience/blob/e6f030b1b2ab8ed8936538181e414dc50df11a2b/sdk/service/partner/conversion-tracking-service.d.ts#L89-L95)
	- This will return data about all of the pages on the site in order to be able to surface them as choices in the app

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Implementation of async functions that satisfy the following PAX partner services:
    * `ConversionTrackingService.getSupportedConversionLabels()`: Should return an object containing an array of supported labels (see [here](https://github.com/google/partner-ads-experience/blob/6a823ebf8ed4e9d121ca8fc2279878a52cad4d19/sdk/service/partner/conversion-tracking-service.d.ts#L29-L39))
        * For the sake of the MVP pilot app, this list should be empty, i.e `{ conversionLabels: [] }`
    * `ConversionTrackingService.getPageViewConversionSetting()`: Should return an object containing the following properties:
        * `enablePageViewConversion`: A boolean value of whether to allow page_view conversion goal type. Will be set to `true` for now, may become conditional at a later stage
        * `websitePages`: An array of page names and their paths (not URLs) as objects with properties `title` and `path`, both strings (see [here](https://github.com/google/partner-ads-experience/blob/e6f030b1b2ab8ed8936538181e414dc50df11a2b/sdk/service/partner/conversion-tracking-service.d.ts#L59C1-L70C2))
        * Said async function should be defined as a function within the base services provided to PAX by the infra established in #8556
        * This page data should be obtained via the core WP pages REST endpoint
            * It should only contain query for published pages
            * It should only query for posts of type `page`
            * It should employ a posts per page limit of 100, with no pagination required at this point in time

## Implementation Brief

* [ ] Within the `createPaxServices` utility function:
	* Define the `conversionTrackingService` as part of the returned services
    * [ ] Define the function for `conversionTrackingService.getSupportedConversionLabels`
        * [ ] This function should return an object of the following shape: `{ conversionLabels: string[] }`
        * [ ] For the sake of the MVP, this array should be left empty, example function definition:
        ```
        const getSupportedConversionLabels = () => ( { conversionLabels: [] } );
        ```
    * [ ] Define the async function for `conversionTrackingService.getPageViewConversionSetting`
        * This function should return an object like so: 
        ```
        { 
            enablePageViewConversion: true, // Whether to enable the page view conversion goal selection in PAX, force true
            websitePages: [ // Array of page objects containing title and path (not URL)
                {
                    title: 'Foo Title', 
                    path: '/foo/path',
                },
                {
                    title: 'Bar Title', 
                    path: '/bar/path',
                },
                ...
            ]
        }
        ```
        * [ ] `websitePages` property data should be obtained via a REST call to the WordPress core API (`GET /wp/v2/pages` using `wp.apiFetch`) with the following arguments:
            * `per_page` 100 
            * `status` publish
        * [ ] Pages (data) obtained via the WordPress REST request should be filtered to only include the following properties per object returned: `title.rendered`, `link` 
            * [ ] Data should be further mapped so that the value of `title.rendered` is assigned to the `title` property instead (for the purpose of passing the data to `websitePages`), the `link` property should be renamed to `path` and its value (by default a URL) processed accordingly so that only the path is returned as the property value
            * [ ] The final shape of the data returned from the WordPress REST request after filtering should match the schema of the `websitePages` property in the code above
        * [ ] If there is an error obtaining the data via a core WordPress REST request, an empty array should be assigned to `websitePages` property

### Test Coverage

* Update `createPaxServices` function tests to verify that these services return data as expected

## QA Brief (QA:ENG)
- Choose an ads related view component to test the services in, i.e `SettingsView`
- Import the `createPaxServices` function from the services file:
```
import { createPaxServices } from './../../pax/services';
```
- Import `useRegistry` from `Data`
```
const { useRegistry, useSelect } = Data;
```
- In the component, instantiate a new PaxServices const:
```
const registry = useRegistry();
const paxServices = createPaxServices( registry );
```
- Log the output of the `conversionTrackingService.getPageViewConversionSetting()` pax service:
```
console.log(
		paxServices.conversionTrackingService.getPageViewConversionSetting()
	);
``` 
- Multiple requests (promises) will be made as the component (re) renders, ignore this
- Monitor the first promise in the console for resolution
- It should return an object of the following shape:
<img width="565" alt="image" src="https://github.com/google/site-kit-wp/assets/72872375/065192ff-ecb3-414b-a178-0ec5e727eff1">
- Importantly it should contain:
    - An `enablePageViewConversion` property with a value of `true`
    - A `websitePages` property with an array of page objects containing `title` and `path` properties relative to the pages in your WordPress site

## Changelog entry

* Provide conversion tracking service to PAX.

**Comment by aaemnnosttv** [comment]
> * this should be an object containing an empty array, i.e `{[]}`

@10upsimon this isn't a valid value since objects are made up of key-value pairs :)

The response for this call needs to have the shape `{ conversionLabels: string[] }` which is probably what you meant?

> * Should return an object containing an array of page names and their paths (not URLs) as objects with properties `title` and `path`, both strings (see [here](https://github.com/google/partner-ads-experience/blob/e6f030b1b2ab8ed8936538181e414dc50df11a2b/sdk/service/partner/conversion-tracking-service.d.ts#L59C1-L70C2))

Similar to the above, the shape of the response needs to match [the interface](https://github.com/google/partner-ads-experience/blob/e6f030b1b2ab8ed8936538181e414dc50df11a2b/sdk/service/partner/conversion-tracking-service.d.ts#L48-L58) – the AC only describes the `websitePages` portion of it (which is the majority of the work here). For now, I think `enablePageViewConversion` would always be `true`, at least we can start with that and make it conditional if necessary.


> * A means to obtain this page data from the WordPress site should be created, either by exposing the page data via an appropriate API call to a route defined within the Ads module PHP definition(s), or as page data exposed from the Ads module PHP infrastructure to the SK app

I think we can be a little more prescriptive here and call for this to be populated on demand (i.e. API call). In the IB, I think we can opt for using the core WP pages endpoint to get the list (we can create our own later if needed but it shouldn't be necessary for the MVP). We should also specify that these should only be _published_ pages of the `page` post type. Let's also keep it simple regarding pagination and limit the list we query to 100 for now which should be more than enough.

**Comment by aaemnnosttv** [comment]
AC ✅

**Comment by aaemnnosttv** [comment]
Thanks @10upsimon ! I tweaked this to be defined in the common/base services for now as there isn't any real reason why we need it to be defined/passed through the setup component. We can re-evaluate this soon but it seems like the simplest path to start with here. I elaborated on a few details here but otherwise this LGTM!

IB ✅

**Comment by eclarke1** [comment]
@10upsimon please can you add an estimate here?

**Comment by 10upsimon** [comment]
@eclarke1 added points

**Comment by benbowler** [comment]
### ✅ QA:Eng Passed

I reviewed the code changes in develop and followed the QA instructions and can confirm the `getPageViewConversionSetting` service function returns the `enablePageViewConversion` key with the value `true` and `websitePages` key containing the sites pages in the [correct structure](https://github.com/google/partner-ads-experience/blob/e6f030b1b2ab8ed8936538181e414dc50df11a2b/sdk/service/partner/conversion-tracking-service.d.ts#L81-L88).

<details><summary>Screenshot of console output</summary>

<img width="569" alt="Screenshot 2024-05-08 at 08 49 15" src="https://github.com/google/site-kit-wp/assets/119352/113d74c3-2c38-4bdb-9f63-f51314ce5500">


</details>
