### ISSUE TITLE
Create `conversion-tracking.js` Datastore

### ISSUE THREAD

**Issue by 10upsimon** [google/site-kit-wp#8615]
## Feature Description

With Conversion Tracking settings and associated REST controller being defined and complete (see #8612, #8613 & #8614), the appropriate datastore should be defined within the main Site Kit React application. This datastore should define the necessary actions and selectors required to save and retrieve applicable Conversion Tracking settings.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* New datastore partial for conversion tracking settings should be added
* It should handle: fetching, and updating/saving settings leveraging the REST endpoint added in #8613
* When Ads or Analytics settings are saved, the conversion tracking setting is saved as well.

## Implementation Brief

* [x] Add `assets/js/googlesitekit/datastore/site/conversion-tracking.js` 
  * You can use `assets/js/googlesitekit/datastore/site/consent-mode.js` as a starting point
  * Create a fetch store for sourcing the settings data, say `getConversionTrackingSettings`, it should use `core/site/data/conversion-tracking` endpoint for that 
  * Create a fetch store for saving settings, say `saveConversionTrackingSettings`, targeting the same endpoint
  * For the `baseInitialState` include `conversionTrackingSettings.enabled` (dot annotates nesting), and `savedConversionTrackingSettings: undefined`
  * Add `saveConversionTrackingSettings` action that will use the fetch store to save the settings
  * Add `setConversionTrackingEnabled` action, that will yield passed boolean value to the reducer. Reducer should update `state.conversionTrackingSettings.enabled` value
  * Add `getConversionTrackingSettings` resolver that will use `getConversionTrackingSettings` fetch store to source the settings data
  * Add selectors for getting the conversion tracking settings (`state.conversionTrackingSettings`) value from the state, and individual selector for retrieving only nested `enabled` value.
  * Add `hasConversionTrackingSettingChanged` selector that compares the difference between `state.conversionTrackingSettings` and `state.savedConversionTrackingSettings` objects, and returns `true` if no difference is found.
* [x] Include new datastore partial to the `assets/js/googlesitekit/datastore/site/index.js` main datastore
* [x] Update `assets/js/modules/ads/datastore/settings.js` and `assets/js/modules/analytics-4/datastore/settings.js`
  * In `submitChanges` function
    * After `saveSettings` is successfuly done (no errors), check if conversion tracking settings changed (`hasConversionTrackingSettingChanged`) to invoke `saveConversionTrackingSettings` action on `CORE_SITE` store to save conversion tracking setting

### Test Coverage

* Add tests for the datastore, testing the actions/resolvers/selectors

## QA Brief

* Setup Site Kit with `conversionInfra` feature flag
* Go to dashboard or setting screen and paste this snippet: `googlesitekit.data.select('core/site').getConversionTrackingSettings()`
  * Firs it will return undefined, you can either check in network tab that response returns default settings value, or paste same snippet again in console which will output the settings
* Paste `googlesitekit.data.dispatch('core/site').setConversionTrackingEnabled(true)` to change the `enabled` value, you can use `true` or `false`
  * You can verify the state change by using the first snippet, which will output the state
* Paste `googlesitekit.data.dispatch('core/site').saveConversionTrackingSettings()`
  * Verify in the network tab that request is sent to the server with properly set `enabled` value
* Refresh the page, use the first snippet again, verify that default value is now `true`
* Paste `googlesitekit.data.select('core/site').haveConversionTrackingSettingsChanged()`
  * It should output `false` as no change happened yet
* Use `googlesitekit.data.dispatch('core/site').setConversionTrackingEnabled(false)` to change the value, and use the snippet from previous step again, it should output `true` as settings were updated in the state
* At any point you can also use `googlesitekit.data.select('core/site').isConversionTrackingEnabled()` to verify the current value in the state. When value is set to `true` it should output it as `true`, otherwise it should be `false`

## Changelog entry

* Implement the new conversion tracking partial datastore.

**Comment by 10upsimon** [comment]
AC LGTM here, but noting that during IB we may want to consider a selector to check if conversion tracking is enable via a selector such as `isConversionTrackingEnabled()` or similar.

**Comment by eugene-manuilov** [comment]
Thanks, @zutigrm. IB technically looks good to me, but I think we need to add one more thing to it. We need to make sure that when Ads or Analytics settings are saved, the conversion events tracking setting is saved as well. In order to do that, we need to call the save action from within the appropriate submit changes functions for both modules when main settings for the module are saved.

**Comment by eugene-manuilov** [comment]
> * Before or after `saveSettings` is called, invoke `saveConversionTrackingSettings` action on `CORE_SITE` store to save conversion tracking setting

@zutigrm this should happen after settings have been successfully saved and only if the conversion tracking setting has changed.

**Comment by zutigrm** [comment]
@eugene-manuilov thanks, IB updated

**Comment by eugene-manuilov** [comment]
Thanks, almost looks good. The last thing let's rename `canSubmitConversionTrackingSettings` to `hasConversionTrackingSettingChanged` since that is the more relevant name for that selector.

**Comment by zutigrm** [comment]
@eugene-manuilov IB updated. Thanks

**Comment by eugene-manuilov** [comment]
Thanks, IB :heavy_check_mark:

**Comment by mohitwp** [comment]
### QA Update ⚠️ 

@zutigrm As per AC - `When Ads or Analytics settings are saved, the conversion tracking setting is saved as well.` But, I've noticed that if analytics or ads module both are not connected then also I'm getting the snippet response and able to save conversion tracking settings. Is this expected ?


**PASS CASES**


- Tested on dev environment.
- Verified on both dashboard and settings page.
- Verified when 'conversionInfra' feature flag is enabled.
- Verified when 'conversionInfra' feature flag is not enabled.
- Verified when Ads or Analytics module are not connected.


<details>

1) Go to dashboard or setting screen and paste this snippet: `googlesitekit.data.select('core/site').getConversionTrackingSettings()`

![image](https://github.com/google/site-kit-wp/assets/94359491/989aaf4d-0a6f-4560-b979-76c8fb18d09f)

2) Paste` googlesitekit.data.dispatch('core/site').setConversionTrackingEnabled(true)` to change the enabled value, you can use true or false

![image](https://github.com/google/site-kit-wp/assets/94359491/b6bea645-faa4-4043-8ad7-025814a9e75a)

**True State:**

![image](https://github.com/google/site-kit-wp/assets/94359491/79d027dc-e7d5-4579-9972-51af1a0b349c)

**False State:**

![image](https://github.com/google/site-kit-wp/assets/94359491/0dc61a03-8122-4e25-84da-ff04d21dba47)

3) Paste `googlesitekit.data.dispatch('core/site').saveConversionTrackingSettings()`
Verify in the network tab that request is sent to the server with properly set enabled value

![image](https://github.com/google/site-kit-wp/assets/94359491/3f44ab7e-1d34-4b9d-8a30-5e75db9f1850)


![image](https://github.com/google/site-kit-wp/assets/94359491/540e48f9-ee7e-48b4-b6b4-028795318ae2)

4)  aste googlesitekit.data.dispatch('core/site').saveConversionTrackingSettings()
Verify in the network tab that request is sent to the server with properly set enabled value


https://github.com/google/site-kit-wp/assets/94359491/c43fb73e-27ae-4987-9593-b86419265376



5) Past`e googlesitekit.data.select('core/site').haveConversionTrackingSettingsChanged()`
It should output false as no change happened yet

![image](https://github.com/google/site-kit-wp/assets/94359491/4726ad27-d2c1-4659-913e-06d6e61ed202)

6) Use googlesitekit.data.dispatch('core/site').setConversionTrackingEnabled(false) to change the value, and use the snippet from previous step again, it should output true as settings were updated in the state

![image](https://github.com/google/site-kit-wp/assets/94359491/d2ce299a-d2c0-43e8-9c08-6fe7e384aaec)


![image](https://github.com/google/site-kit-wp/assets/94359491/47140b4a-3124-4cbc-b389-22491fe39b4c)

7) Current value state-

![image](https://github.com/google/site-kit-wp/assets/94359491/75b129c6-6ef4-4f33-8295-0ac9d845023a)

_When 'ConversionInfra' feature flaf is not enabled_

![image](https://github.com/google/site-kit-wp/assets/94359491/9321d9f2-6e54-4a20-a4a9-002d79c25bad)



_When both 'Analytics' and Ads module not connected_

![image](https://github.com/google/site-kit-wp/assets/94359491/a80e84fe-3166-4336-9559-12e562213f6a)

</details>

**Comment by mohitwp** [comment]
@zutigrm 

- I created a new site on dev environment. 
- Setup Site Kit without Analytics.
- Also, not setup Ads module.
- On dashboard or settings page I pasted the snippet as per QAB.
- Changed the state from 'False' to 'True' and it's getting save.
- I'm getting response as per QAB without setting up Analytics or Ads module.

Note : It's a fresh site on which site kit was never setup. 

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/d8552639-1f51-4418-8bc7-ccb289976a3a)

![image](https://github.com/google/site-kit-wp/assets/94359491/454a626e-85db-48cc-ab3f-cc076a93146b)

![image](https://github.com/google/site-kit-wp/assets/94359491/01abee96-29ed-4f1b-aa99-06f212f5e668)

</details>

**Comment by zutigrm** [comment]
@mohitwp That's fine since you are triggering it manually. In real usage the setting is saved only once button to save settings changes is hit on the settings screen of those 2 modules. Conversion event is independent and shared between these two modules, so manually invoking settings will still work independently of whether the modules are active or not

**Comment by mohitwp** [comment]
### QA Update ✅ 

Thanks @zutigrm !

- Tested on dev environment.
- Verified on both dashboard and settings page.
- Verified when 'conversionInfra' feature flag is enabled.
- Verified when 'conversionInfra' feature flag is not enabled.
- Verified when Ads or Analytics module are not connected.


<details>

1) Go to dashboard or setting screen and paste this snippet: `googlesitekit.data.select('core/site').getConversionTrackingSettings()`

![image](https://github.com/google/site-kit-wp/assets/94359491/989aaf4d-0a6f-4560-b979-76c8fb18d09f)

2) Paste` googlesitekit.data.dispatch('core/site').setConversionTrackingEnabled(true)` to change the enabled value, you can use true or false

![image](https://github.com/google/site-kit-wp/assets/94359491/b6bea645-faa4-4043-8ad7-025814a9e75a)

**True State:**

![image](https://github.com/google/site-kit-wp/assets/94359491/79d027dc-e7d5-4579-9972-51af1a0b349c)

**False State:**

![image](https://github.com/google/site-kit-wp/assets/94359491/0dc61a03-8122-4e25-84da-ff04d21dba47)

3) Paste `googlesitekit.data.dispatch('core/site').saveConversionTrackingSettings()`
Verify in the network tab that request is sent to the server with properly set enabled value

![image](https://github.com/google/site-kit-wp/assets/94359491/3f44ab7e-1d34-4b9d-8a30-5e75db9f1850)


![image](https://github.com/google/site-kit-wp/assets/94359491/540e48f9-ee7e-48b4-b6b4-028795318ae2)

4)  aste googlesitekit.data.dispatch('core/site').saveConversionTrackingSettings()
Verify in the network tab that request is sent to the server with properly set enabled value


https://github.com/google/site-kit-wp/assets/94359491/c43fb73e-27ae-4987-9593-b86419265376



5) Past`e googlesitekit.data.select('core/site').haveConversionTrackingSettingsChanged()`
It should output false as no change happened yet

![image](https://github.com/google/site-kit-wp/assets/94359491/4726ad27-d2c1-4659-913e-06d6e61ed202)

6) Use googlesitekit.data.dispatch('core/site').setConversionTrackingEnabled(false) to change the value, and use the snippet from previous step again, it should output true as settings were updated in the state

![image](https://github.com/google/site-kit-wp/assets/94359491/d2ce299a-d2c0-43e8-9c08-6fe7e384aaec)


![image](https://github.com/google/site-kit-wp/assets/94359491/47140b4a-3124-4cbc-b389-22491fe39b4c)

7) Current value state-

![image](https://github.com/google/site-kit-wp/assets/94359491/75b129c6-6ef4-4f33-8295-0ac9d845023a)

_When 'ConversionInfra' feature flaf is not enabled_

![image](https://github.com/google/site-kit-wp/assets/94359491/9321d9f2-6e54-4a20-a4a9-002d79c25bad)



_When both 'Analytics' and Ads module not connected_

![image](https://github.com/google/site-kit-wp/assets/94359491/a80e84fe-3166-4336-9559-12e562213f6a)

</details>
