### ISSUE TITLE
Copy on Enhanced Conversion Tracking Toggle for Analytics Module Needs Changing

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#8816]
## Bug Description

[As reported in Asana](https://app.asana.com/0/1207432565654530/1207469198853224/f) on the bug bashing by @kelvinballoo 

The copy on the Analytics module edit mode is incorrect when comparing it to the Figma designs. 

Based on Figma, it should be:
`Conversion tracking is used for tracking additional conversion-related events via Analytics`

Currently it reads:
`Conversion tracking allows you to measure additional events on your site from other plugins that Site Kit integrates with to optimize your campaign performance.  Learn more`

Please note that there isn't a learn more link in the figma designs but from the conversation in Asana, it should be added.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

*`ConversionTrackingToggle` component should render copy dynamically. It should show:
  * `Conversion tracking is used for tracking additional conversion-related events via Analytics` when on Analytics module
  * Currently used copy `Conversion tracking allows you to measure additional events on your site from other plugins that Site Kit integrates with to optimize your campaign performance.  Learn more` when on Ads module
 

## Implementation Brief

* [ ] Update `assets/js/components/conversion-tracking/ConversionTrackingToggle.js` 
  * Render the `children` instead of currently hardcoded content https://github.com/google/site-kit-wp/blob/817317dfc6e20c72f3637bf823db540f247af6bc/assets/js/components/conversion-tracking/ConversionTrackingToggle.js#L103-L120
* [ ] Update `assets/js/modules/ads/components/settings/SettingsForm.js`
  * Use the content previously present in the `ConversionTrackingToggle` component and use it as a wrapper, to add the content element as child
* [ ] Update `assets/js/modules/analytics-4/components/settings/SettingsForm.js`
  * Use the content referenced in the AC for Analytics module and add it as translatable string wrapped under `ConversionTrackingToggle` component

### Test Coverage

* Update any failing VRT

## QA Brief

* Set up Site Kit with the Analytics and Ads modules enabled.
* Visit Site Kit Settings and open the Analytics' modules settings, then click "Edit" to open the edit mode
  * Ensure the text underneath the "Enhanced Conversion Tracking" toggle reads: _Conversion tracking is used for tracking additional conversion-related events via Analytics_
* Visit Site Kit Settings and open the Ads' modules settings, then click "Edit" to open the edit mode
  * Ensure the text underneath the "Enhanced Conversion Tracking" toggle reads: _ Conversion tracking allows you to measure additional events on your site from other plugins that Site Kit integrates with to optimize your campaign performance. Learn more_

## Changelog entry

* Update copy for the Enhanced Conversion Tracking toggle to be different for the Analytics module.

**Comment by zutigrm** [comment]
Since it is a very straightforward issue, I added IB at the same time as AC

**Comment by eugene-manuilov** [comment]
@zutigrm let's use `children` instead of `content`.

**Comment by eugene-manuilov** [comment]
Thanks. IB ✔️

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Verified that Analytics copy updated to `Conversion tracking is used for tracking additional conversion-related events via Analytics .Verified the Ads module copy - the text underneath the "Enhanced Conversion Tracking" toggle reads: _ C`onversion tracking allows you to measure additional events on your site from other plugins that Site Kit integrates with to optimize your campaign performance. Learn more_`

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/f4e56cc9-06fe-44eb-8c3a-ef501c904293)

![image](https://github.com/google/site-kit-wp/assets/94359491/88ea90fb-01c4-4aed-a226-6754199007dd)

![image](https://github.com/google/site-kit-wp/assets/94359491/fc5cb2f0-9626-4ef9-b2a2-e66306455270)

</details>
