### ISSUE TITLE
Add Tracking To The Conversion Tracking Toggle

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#8894]
## Feature Description

The Enhanced Conversion Tracking toggle should track internal events following the example of other toggles.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Event category for all events should be `${viewContext}`
* When enhanced conversion tracking toggle is switched, an event should be tracked in following way:
  * When the toggle is enabled the event name to track should be `ect_enable`
  * When the toggle is disabled the event name to track should be `ect_disable`
* When the disable modal is shown - upon trying to disable the toggle:
  * When the modal is in view, track an event with name `ect_view_modal` 
  * When clicking the confirm button (to continue with disabling the tracking) in modal, track an event with name `ect_confirm_disable`
  * When canceling the modal (choosing not to disable the conversion tracking) track an event with name `ect_cancel_disable` 

## Implementation Brief

* [x] All events should have category name defined in AC
* [x] Update `assets/js/components/conversion-tracking/ConversionTrackingToggle.js`
  * You can check `assets/js/components/consent-mode/ConsentModeSwitch.js` for an example as it has similar events/behaviour
  * In the main `Switch`, in `onClick` under `isConversionTrackingEnabled` check track `ect_disable`, and in `else` condition check track `ect_enable`
  * Update `ConfirmDisableConversionTrackingDialog` component
    * In `onConfirm` callback, include event tracking for `ect_confirm_disable`
    * In `onCancel` callback include event tracking for `ect_cancel_disable`
* [x] Update `assets/js/components/conversion-tracking/ConfirmDisableConversionTrackingDialog.js`
  * Add `useMount` hook and track `ect_view_modal` event name

### Test Coverage

* No updates needed

## QA Brief

* Setup Site Kit and connect Ads module
* Go to settings edit screen of Ads module
* Verify that events listed in the AC are tracked as defined

## Changelog entry

* Added events tracking to the conversion tracking toggle.

**Comment by binnieshah** [comment]
@aaemnnosttv please could you confirm what could be used for the event name used for tracking? We can then complete the AC for this, thanks!

**Comment by binnieshah** [comment]
from Slack:  I've added the events to [our sheet ](https://docs.google.com/spreadsheets/d/1eEuJ2ppVZuai1_hL77RA2vL7DUidM_qCnvTsjxZ_S4k/edit#gid=925918307) where these our defined to a new section for "Enhanced Conversion Tracking". It should be all we need for defining 8894

**Comment by 10upsimon** [comment]
@zutigrm assigning back to you in AC for now as we have internal ongoing discussions at present to decide on the event names for the modal actions as well. I'll udpate you once we have them and we can update the AC and return to me for ACR.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

Checked the events for Ads as per QAB, but also made sure Analytics toggle triggered the events too. 

- When enhanced conversion tracking toggle is switched, an event is tracked in following ways:
  - When the toggle is enabled the event name to track is `ect_enable`
  - When the toggle is disabled the event name to track is `ect_disable`
- When the disable modal is shown - upon trying to disable the toggle:
  - When the modal is in view, track an event with name `ect_view_modal`
  - When clicking the confirm button in modal, track an event with name `ect_confirm_disable`
  - When canceling the modal track an event with name `ect_cancel_disable`
