### ISSUE TITLE
Setup completion tracking no longer working as expected

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#9039]
## Bug Description

There are a few internal events that are tracked to measure the success of SK onboarding flows which complement `start_site_setup` and `start_user_setup` events respectively.

- `complete_site_setup` when the initial SK setup is completed
- `complete_user_setup` when a user successfully signs in with Google (initial connection, not each time when granting new scopes)

These are currently implemented in our success banner component which isn't really the right place (for a few reasons) anyways.

## Steps to reproduce

1. Setup SK with tracking opted-in
2. See these events aren't tracked

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The following internal GA events should be reimplemented and their current non-functional implementations removed
* Reasonable effort should be taken to avoid duplicate tracking so as to capture the event once per start

Event Name | Category | Label | Trigger | Condition
-- | -- | -- | -- | --
`complete_site_setup` | `{viewContext}_setup` | `proxy` or `custom-oauth` | SK Page load | Initial SK setup is completed
`complete_user_setup` | `{viewContext}_setup` | `proxy` or `custom-oauth` | SK Page load | Initial user connection is completed (becomes authenticated)

Note: these events are not mutually exclusive

## Implementation Brief

* [ ] Update the points where starting site and user setup are tracked (both proxy + GCP components) to set a flag in client side cache to mark the beginning of the event/journey (introducing a utility may be a good idea)
	- The cache related behavior doesn't need to be conditional based on tracking opt-in as it's local state only
* [ ] Introduce a new custom hook for global tracking effects (e.g. `useGlobalTrackingEffect`)
	- For now this can simply check for the added cache flags on page load, and if present, conditionitionally track these events as defined in the AC
		- Before calling `trackEvent`, delete the related cache item for the event about to be tracked. This way it shouldn't be necessary to also track state for the purpose of avoiding duplicate tracking
	- In the past, we've used a `useMount` for this kind of thing but we could probably also use a normal `useEffect` with `viewContext` as the dependency as a more SPA-friendly approach (if/when we get there)
* [ ] Update the `Header` component to use the new effect
	- Putting this in the `Header` ensures that these events are tracked reliably in situations where a user might not land back on the dashboard right away (such as the site setup including GA)
* [ ] Update `SetupSuccessBannerNotification` to remove everything related to the tracking of these events

### Test Coverage

* Add test coverage for the added hook

## QA Brief

* Tick the tracking checkbox `Help us improve Site Kit by sharing anonymous usage data.` and start the Site Kit setup
* Verify that events listed in AC are being tracked after successful setup, regardless of setting it up with GA4 or without
  * Verify that if you cancel the flow and return back to initial screen with an error message, events are _not_ tracked
* Confirm this for GCP flow as well. You can check this [thread](https://fueled10up.slack.com/archives/CBKKQEBR9/p1721654557242699) on info how to trigger the GCP flow
* Connecting/signing in from view only dashboard menu `Sign in with Google`, upon returning `complete_user_setup` event should be tracked

## Changelog entry

* Fix measurement of successful setup completion events.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@zutigrm I have three observations:

1. The `complete_site_setup` and `complete_user_setup` GA events are not getting triggered when setting up Site Kit with the GCP flow.  I tried this on two different sites. 
2. I am unable to see the `complete_user_setup` GA event being triggered when connecting/signing in from view only dashboard menu `Sign in with Google`  See screencast. 
3. On the splash screen where it says, `Site Kit has already been configured by another admin of this site. ` and I set up Site Kit with another Google account, and 2nd admin user, the GA events are not getting triggered here. This might be expected but would like to check. 

https://github.com/user-attachments/assets/25ecd82c-cada-4cc3-b180-470f0215987f

**Verified:**

- Events listed in AC are being tracked after successful setup, regardless of setting it up with or without GA4. 
- When I cancel the flow and return back with an error message, events are not tracked. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/user-attachments/assets/1301db28-d786-4158-8ff5-0061c2f54d6f)
![image](https://github.com/user-attachments/assets/984e2cf4-75c4-48b2-b1a8-c8e17972697f)
![image](https://github.com/user-attachments/assets/e2c60319-db12-44fc-abf4-507ee32e45bd)
![image](https://github.com/user-attachments/assets/f4f8157c-1fde-44dc-a8a0-7ccc35712aa4)
![image](https://github.com/user-attachments/assets/f2b1910a-8e8e-4d35-a29f-ba150ce3686c)
![image](https://github.com/user-attachments/assets/c85941d4-0d2a-4139-8cce-aa8d7ec2eb6b)
![image](https://github.com/user-attachments/assets/e52c6f42-c563-4ce1-8d5c-40fcced08063)

</details>

**Comment by zutigrm** [comment]
Thanks @wpdarren , the points 2 & 3 were just an added bonus not something it was tracked before, so I will remove tracking from view only, as it will consume to much effort, will focus only on first point around GCP setup

**Comment by aaemnnosttv** [comment]
@wpdarren I was just looking at this with @zutigrm and confirmed the only issue to fix here is around the tracking when not using the proxy. We verified that the second admin is tracked correctly as well as the sign in from the view-only user menu. It seems the reason you didn't see it is due to not opting in to the tracking, as can be seen in your screencast so that would be WAI ;)

@zutigrm is working on finishing up his follow-up PR for the GCP side and this should be back in QA soon.

**Comment by aaemnnosttv** [comment]
Back to you @wpdarren 👍

**Comment by wpdarren** [comment]
@aaemnnosttv  oops, that was stupid of me, noted. 

### QA Update: ⚠️ 

@zutigrm I noticed on the GCP side that the `complete_user_setup` is getting triggered but I can't see `complete_site_setup` GA Event. I have tried this a few times. I made sure oAuth was cleared, and also local and session storage.  According to the AC this should be tracked but not seeing this.  Could you take a look? 

https://github.com/user-attachments/assets/1ba3260c-4df8-4010-b410-bce7a577a81d

**Comment by zutigrm** [comment]
Thanks @wpdarren , I left my comment in [slack thread](https://fueled10up.slack.com/archives/C0788NZMLF2/p1721868839786809), with some info for @aaemnnosttv , as I will need his confirmation on the direction, TLDR - since connected status is always `true` we will need to always track site setup event, regardless if Site Kit is setup first time or by secondary admins.

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Events listed in AC are being tracked after successful setup, regardless of setting it up with or without GA4. 
- When I cancel the flow and return back with an error message, events are not tracked. 

Note: we decided not to concern ourselves with GCP GA events, and I can confirm for the events are getting tracked as per the AC after successful setup, regardless of setting it up with GA4 or without. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/user-attachments/assets/1301db28-d786-4158-8ff5-0061c2f54d6f)
![image](https://github.com/user-attachments/assets/984e2cf4-75c4-48b2-b1a8-c8e17972697f)
![image](https://github.com/user-attachments/assets/e2c60319-db12-44fc-abf4-507ee32e45bd)
![image](https://github.com/user-attachments/assets/f4f8157c-1fde-44dc-a8a0-7ccc35712aa4)
![image](https://github.com/user-attachments/assets/f2b1910a-8e8e-4d35-a29f-ba150ce3686c)
![image](https://github.com/user-attachments/assets/c85941d4-0d2a-4139-8cce-aa8d7ec2eb6b)
![image](https://github.com/user-attachments/assets/e52c6f42-c563-4ce1-8d5c-40fcced08063)

</details>
