### ISSUE TITLE
Remove UA from internal tracking

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#9042]
## Feature Description

Universal Analytics has stopped tracking all hits since July 1 2024, it can now be removed from the plugin.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The tracking configuration [specific to UA](https://github.com/google/site-kit-wp/blob/84f0b628238b3d2ad40eb8b80a190dc6249d15ff/assets/js/util/tracking/createInitializeSnippet.js#L62-L72) should be removed
* The tracking ID should be updated in `\Google\Site_Kit\Core\Tracking\Tracking`
	* `trackingID_GA4` can be removed / replaced with the above (as it was before there were multiple IDs)

## Implementation Brief

* [ ] Update the `TRACKING_ID` const at [includes/Core/Tracking/Tracking.php](https://github.com/google/site-kit-wp/blob/develop/includes/Core/Tracking/Tracking.php#L30) and replace the value with that of the GA4 tracking ID
* [ ] In [assets/js/util/tracking/createInitializeSnippet.js](https://github.com/google/site-kit-wp/blob/develop/assets/js/util/tracking/createInitializeSnippet.js)
    * [ ] Remove the `dataLayerPush` code block referencing `config.trackingID`
    https://github.com/google/site-kit-wp/blob/45342dd6ea117deeb7c7af041707488b1fcf7161/assets/js/util/tracking/createInitializeSnippet.js#L62-L72
    * [ ] Update the `dataLayerPush` code block referencing `config.trackingID_GA4` and update it to instead reference `config.trackingID`
    https://github.com/google/site-kit-wp/blob/45342dd6ea117deeb7c7af041707488b1fcf7161/assets/js/util/tracking/createInitializeSnippet.js#L73-L85
* [ ] In [assets/js/util/tracking/index.js](https://github.com/google/site-kit-wp/blob/develop/assets/js/util/tracking/index.js)
    * [ ] Remove `trackingID_GA4` from the `initialConfig` object
    https://github.com/google/site-kit-wp/blob/45342dd6ea117deeb7c7af041707488b1fcf7161/assets/js/util/tracking/index.js#L37-L48

### Test Coverage

* [ ] Update the test at [assets/js/util/tracking/index.test.js](https://github.com/google/site-kit-wp/blob/develop/assets/js/util/tracking/index.test.js) accordingly following the above changes 

## QA Brief

* Setup Site Kit
* Enable Analytics event tracking debugger extension (like adswerve, etc) in the browser of your choice 
* Opt in for tracking in Site Kit Settings
* Verify (in analytics debugger output) that UA tag ID is not present (`UA-xxx`), but only the GA4 one `G-xxx` 

## Changelog entry

* Remove UA Analytics tracking from Site Kit admin.

**Comment by eugene-manuilov** [comment]
IB ✔️

**Comment by mohitwp** [comment]
### QA Update ✅ 

- Tested on dev environment.
- Tested using GA debugger.
- Verified on dev environment that UA tag ID is not present (UA-xxx).
- Verified that GA tag is showing.


<details>

**Latest Environment -**

![image](https://github.com/user-attachments/assets/3fad5c6b-06c3-4b12-92ea-f83bf497d743)

![image](https://github.com/user-attachments/assets/009d175d-9a89-4fea-86b1-48fe8832e79f)

**Dev environment -**

![image](https://github.com/user-attachments/assets/49d573bd-37bd-440a-967a-8762c47a9c03)


**Screencast -**


https://github.com/user-attachments/assets/d6307bbc-ef01-492b-8d2f-8e17e55136b2

</details>
