### ISSUE TITLE
Implement Internal Measurement/Tracking Following ACR KMW Updates

### ISSUE THREAD

**Issue by 10upsimon** [google/site-kit-wp#9181]
## Feature Description

As the final body of work relating to the Analytics Conversion Tracking (ACR) epic, internal measurement/tracking should be implemented so that Site Kit can better understand the uptake, usage and success/failure of this feature. This tracking should leverage existing tracking means used throughout the codebase.

This tracking involves updates to existing KMW tracking infrastructure/implementations, as well as the introduction of new tracking against ACR elements introduced within this epic. 

Tracking will cover the following areas:

- Inline banners/notifications/CTA's within the main dashboard introduced during this epic
- Inline banners/notifications/CTA's within the settings area introduced during this epic
- Existing metric selection sidebar tracking functionality will be extended to flag ACR selections upon save
    - Existing KMW tracking will updated to conditionally contain a `conversion_reporting` event label when the same event is being tracked for ACR and non-ACR scenarios

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Internal tracking is to be implemented on all new banners/notifications/CTA's introduced as part of the ACR work
    * The existing `trackEvent` function should be leveraged, as it is throughout the Site Kit application
    * The [[SK] Google Analytics Custom Events](https://docs.google.com/spreadsheets/d/1eEuJ2ppVZuai1_hL77RA2vL7DUidM_qCnvTsjxZ_S4k/edit?gid=925918307#gid=925918307) tracking sheet should be used as a source of truth for the events, namely lines under the "[Key Metrics Widget (Conversion Reporting Specific)](https://docs.google.com/spreadsheets/d/1eEuJ2ppVZuai1_hL77RA2vL7DUidM_qCnvTsjxZ_S4k/edit?gid=925918307#gid=925918307&range=336:336)" row header
 
* The banner/notice/CTA components that should have tracking events applied to them should be as follows:
    * ### Conversion Events Detected for Tailored KMW Users
    * ![Image](https://github.com/user-attachments/assets/541bcc5a-5866-48ab-973a-005ad2296575)
        * Event Name: `view_notification`
        * Category: `{viewContext}_kmw-tailored-conversion-events-detected-notification`
        * Label: `conversion_reporting`
        * Trigger: `Element visibility`
        - -----
        * Event Name:	`confirm_add_new_conversion_metrics`
        * Category: `{viewContext}_kmw-tailored-conversion-events-detected-notification`
        * Label: `conversion_reporting`
        * Trigger:	`Click`
        - -----
        * Event Name:	`dismiss_notification`
        * Category: `{viewContext}_kmw-tailored-conversion-events-detected-notification`
        * Label: `conversion_reporting`
        * Trigger: `Click`
    * ### Conversion Events Detected for Manually Selected KMW Users
    * ![Image](https://github.com/user-attachments/assets/5d364f83-c062-425e-ad26-da0fb1b4265e)
        * Event Name: `view_notification`
        * Category: `{viewContext}_kmw-manual-conversion-events-detected-notification`
        * Label: `conversion_reporting`
        * Trigger: `Element visibility`
        - -----
        * Event Name:	`confirm_select_new_conversion_metrics`
        * Category: `{viewContext}_kmw-manual-conversion-events-detected-notification`
        * Label: `conversion_reporting`
        * Trigger:	`Click`
        - -----
        * Event Name:	`dismiss_notification`
        * Category: `{viewContext}_kmw-manual-conversion-events-detected-notification`
        * Label: `conversion_reporting`
        * Trigger: `Click`
    * ### New Conversion Events Detected for Manually Selected KMW Users
    * ![Image](https://github.com/user-attachments/assets/8e4c9190-9ac0-4030-9a25-d9147d27cd53)
        * Event Name: `view_notification`
        * Category:`{viewContext}_kmw-manual-new-conversion-events-detected-notification`
        *  Label: `conversion_reporting`
        * Trigger: `Element visibility`
        - -----
        * Event Name:	`confirm_view_new_conversion_metrics`
        * Category: `{viewContext}_kmw-manual-new-conversion-events-detected-notification`
        * Label: `conversion_reporting`
        * Trigger:	`Click`
        - -----
        * Event Name:	`dismiss_notification`
        * Category: `{viewContext}_kmw-manual-new-conversion-events-detected-notification`
        * Label: `conversion_reporting`
        * Trigger: `Click`
    * ### New Conversion Events Detected for Tailored KMW Users
    * ![Image](https://github.com/user-attachments/assets/8e4c9190-9ac0-4030-9a25-d9147d27cd53)
        * Event Name: `view_notification`
        * Category:`{viewContext}_kmw-tailored-new-conversion-events-detected-notification`
        *  Label: `conversion_reporting`
        * Trigger: `Element visibility`
        - -----
        * Event Name:	`confirm_view_new_conversion_metrics`
        * Category: `{viewContext}_kmw-tailored-new-conversion-events-detected-notification`
        * Label: `conversion_reporting`
        * Trigger:	`Click`
        - -----
        * Event Name:	`dismiss_notification`
        * Category: `{viewContext}_kmw-tailored-new-conversion-events-detected-notification`
        * Label: `conversion_reporting`
        * Trigger: `Click`
    * ### Banner Encouraging Existing User Input Users to Edit Purpose Answer
    * ![Image](https://github.com/user-attachments/assets/6a726ad1-56e0-48ca-97e5-bd4b5756f5db)
        * Event Name: `view_notification`
        * Category: `{viewContext}_kmw-settings-suggested-site-purpose-edit-notificaton`
        * Label: `conversion_reporting`
        * Trigger: `Element visibility`
        - -----
        * Event Name:	`confirm_notification`
        * Category: `{viewContext}_kmw-settings-suggested-site-purpose-edit-notificaton`
        * Label: `conversion_reporting`
        * Trigger: `Click`
    * ### Tailored Metrics Suggestion Modal
    * ![Image](https://github.com/user-attachments/assets/e1f5475d-09d5-4ba8-a6a7-ff2ecde72e76)
        * Event Name: `confirm_update_metrics_selection`
        * Category: `{viewContext}_kmw-settings-tailored-metrics-suggestions`
        * Label: `conversion_reporting`
        * Trigger: `Element visibility`
        - -----
        * Event Name:	`cancel_update_metrics_selection`
        * Category: `{viewContext}_kmw-settings-tailored-metrics-suggestions`
        * Label: `conversion_reporting`
        *  Trigger: `Click`
    * ### CTA Giving Existing Manual KMW Users The Option to Switch to Tailored
    * ![Image](https://github.com/user-attachments/assets/47a0c7f1-d82b-4ebc-83c0-1185f111398f)
        * Event Name: `view_notification`
        * Category: `{viewContext}_kmw-settings-change-from-manual-to-tailored`
        * Label: `conversion_reporting`
        * Trigger: `Element visibility`
        - -----
        * Event Name:	`confirm_get_tailored_metrics`
        * Category: `{viewContext}_kmw-settings-change-from-manual-to-tailored`
        * Label: `conversion_reporting`
        * Trigger: `Click`
    * ### Lost Events Notification
    * ![Image](https://github.com/user-attachments/assets/e74c152c-bf3a-4945-ad11-e01afe1ca46f)
        * Event Name: `view_notification`
        * Category: `{viewContext}_kmw-lost-conversion-events-detected-notification`
        * Label: `conversion_reporting`
        * Trigger: `Element visibility`
        - -----
        * Event Name:	`confirm_get_select_metrics`
        * Category: `{viewContext}_kmw-lost-conversion-events-detected-notification`
        * Label: `conversion_reporting`
        * Trigger: `Click`
        - -----
        * Event Name:	`dismiss_notification`
        * Category: `{viewContext}_kmw-lost-conversion-events-detected-notification`
        * Label: `conversion_reporting`
        * Trigger: `Click`

 
* The following (existing) KMW tracking action is to be supplemented to support a more informatory tracking overview to gauge ACR success:
    * The existing `metrics_sidebar_save` tracked event within `assets/js/components/KeyMetrics/MetricsSelectionPanel/Footer.js` is updated to contain the label value `conversion_reporting` that explicitly identifies that the saved metrics are conversion event tracking related metrics. The existing events will remain as is, they simply won't have the additional event label added. This will allow the event (and other ACR based events) to be filtered within the GA4 reporting dashboard to ascertain ACR vs non-ACR events.
    * Existing trackEvent calls against KMW metric components should remain as they are, with new KMW components inheriting said tracking automatically, but the addition of an event label with value "Conversion Reporting" be added for Analytics Conversion Reporting specific metrics.

## Implementation Brief

* ### Tracking utility function
    * To simplify the tracking logic and avoid over-cluttering the existing `ConversionReportingNotificationCTAWidget` component, a utility helper function should be created to aid in tracking. This tracking function should accept the variables/constants from `ConversionReportingNotificationCTAWidget` that determine whether there are initial or new events, whether they're manual vs tailored etc, and it should also accept an event string. Implement the utility function by doing the following:
        * Create a new `utils.js` file in the folder at `assets/js/components/KeyMetrics`
        * Import the `trackEvent` function as used to track internal events throughout the codebase
        * Define a new tracking utility function, say `conversionReportingDetectedEventsTracking ` that accepts the following parameters:
            * An object with the following properties, these will be passed from the component file for `ConversionReportingNotificationCTAWidget`:
                * `shouldShowInitialCalloutForTailoredMetrics`
                * `shouldShowCalloutForUserPickedMetrics`
                * `haveConversionEventsWithDifferentMetrics`
                * `userPickedMetrics`
                * `haveLostConversionEvents`
            * `eventName` - The string event name to send with the `trackEvent()` call
        * The tracking category will be dynamically handled within the function body
        *  Within the function body of this utility function, apply the following logic:
            * `if ( haveConversionEventsWithDifferentMetrics && userPickedMetrics?.length ){ ... }` -Call `trackEvent()` for new events with manual KMW selection, set the tracking category to `{viewContext}_kmw-manual-new-conversion-events-detected-notification`
            * `if ( haveConversionEventsWithDifferentMetrics && ! userPickedMetrics?.length ){ ... }` - Call `trackEvent()` for new events with tailored KMW selection, set the tracking category to `{viewContext}_kmw-tailored-new-conversion-events-detected-notification`
            * `if ( shouldShowInitialCalloutForTailoredMetrics ) { ... }` - Call `trackEvent()` for the _initial_ detection of events with tailored KMW selection, set the tracking category to `{viewContext}_kmw-tailored-conversion-events-detected-notification`
            * `if ( shouldShowCalloutForUserPickedMetrics ) { ... }` - Call `trackEvent()` for the _initial_ detection of events with manual KMW selection, set the tracking category to `{viewContext}_kmw-manual-conversion-events-detected-notification`
        * In each of the above  conditional bodies, call the `trackEvent()` function, passing the event name and category dynamically, but a finite string value for the event label:
            * `trackEvent( eventCategory, eventName, 'conversionReporting' );`
            * `return` within each conditional once the `trackEvent()` call has been made
    * An example (but not final) function can be seen below:

```
const conversionReportingDetectedEventsTracking = () => {
  if ( haveLostConversionEvents ) {
    // Track event for lost events, but do not return as other banners can be shown in parallel
  }  

  if ( haveConversionEventsWithDifferentMetrics && userPickedMetrics?.length ) {
    // Track event for new events with manual KMW selection
    return;
  }

  if ( haveConversionEventsWithDifferentMetrics && ! userPickedMetrics?.length ) {
   // Track event for new events with tailored KMW selection
    return;
  }

  if ( shouldShowInitialCalloutForTailoredMetrics ) {
    // Track event for the _initial_ detection of events with tailored KMW selection
    return;
  }

  if ( shouldShowCalloutForUserPickedMetrics ) {
     // Track event for the _initial_ detection of events with manual KMW selection
    return;
  }
}
```

* Implement the necessary `propTypes` for the utility function in question
* Import said new `conversionReportingDetectedEventsTracking()` utility function into the component file at `assets/js/components/KeyMetrics/ConversionReportingNotificationCTAWidget.js` so that it can be used to implement the necessary tracking of events

* ### Build common object required to be passed to the above tracking utility function:
    * Define a new constant, say `trackingArguments`, and add the required properties as per the above tracking helper function, i.e

```
const  conversionReportingDetectedEventsTrackingArgs = {
    shouldShowInitialCalloutForTailoredMetrics, 
    shouldShowCalloutForUserPickedMetrics, 
    haveConversionEventsWithDifferentMetrics, 
    userPickedMetrics,
    haveLostConversionEvents,
};
```
    
* This should be passed to the utility tracking function as the first object parameter 

* ### Conversion Events Detected for Tailored KMW Users
* ![Image](https://github.com/user-attachments/assets/541bcc5a-5866-48ab-973a-005ad2296575)
* ### Conversion Events Detected for Manually Selected KMW Users
* ![Image](https://github.com/user-attachments/assets/5d364f83-c062-425e-ad26-da0fb1b4265e)
* ### New Conversion Events Detected for Manually Selected KMW Users
* ![Image](https://github.com/user-attachments/assets/8e4c9190-9ac0-4030-9a25-d9147d27cd53)
* ### New Conversion Events Detected for Tailored KMW Users
* ![Image](https://github.com/user-attachments/assets/8e4c9190-9ac0-4030-9a25-d9147d27cd53)
* ### Lost Events Notification
* ![Image](https://github.com/user-attachments/assets/e74c152c-bf3a-4945-ad11-e01afe1ca46f)
    * [x] Within the file at `assets/js/components/KeyMetrics/ConversionReportingNotificationCTAWidget.js`:
        * [x] Within the existing `onDismiss` callback, call the `conversionReportingDetectedEventsTracking()` utility tracking function with the following parameters:
            * [x] `trackingArguments`
            * [x] `'dismiss_notification'`
        * [x] Within the existing `handleAddMetricsClick` callback function, call the `conversionReportingDetectedEventsTracking()` utility tracking function with the following parameters:
            * [x] `trackingArguments`
            * [x] `'confirm_add_new_conversion_metrics'`
        * [x] For handling the `view_notification` event, an implementation of a `isViewed` state,  along with the user of `useIntersection` will be necessary:
            * [x] Use the file at `assets/js/components/notifications/BannerNotification/index.js` as a reference for how to implement the `isViewed` state, and use of `useIntersection`
            * [x] Implement the view state and use of `useIntersection` logic (i.e `.isIntersecting`) within a new `useEffect` hook
                * [x] Within the `useEffect` hook, if the component is in view and has not _yet_ been viewed, call the `conversionReportingDetectedEventsTracking()` utility tracking function with the following parameters:
                    * [x] `trackingArguments`
                    * [x] `'view_notification'`

* ### Banner Encouraging Existing User Input Users to Edit Purpose Answer
* ![Image](https://github.com/user-attachments/assets/6a726ad1-56e0-48ca-97e5-bd4b5756f5db)
    * [x] Within the file at `assets/js/components/user-input/KeyMetricsSettingsSellProductsSubtleNotification.js`:
        * [x] Import the `trackEvent` function as used to track internal events throughout the codebase
        * [x] For handling the `view_notification` event, an implementation of a `isViewed` state,  along with the user of `useIntersection` will be necessary:
            * [x] Use the file at `assets/js/components/notifications/BannerNotification/index.js` as a reference for how to implement the `isViewed` state, and use of `useIntersection`
            * [x] Implement the view state and use of `useIntersection` logic (i.e `.isIntersecting`) within a new `useEffect` hook,  if the component is in view and has not _yet_ been viewed, call the `trackEvent()` function and pass the following parameters:
                * [x] `{viewContext}_kmw-settings-suggested-site-purpose-edit-notification`
                * [x] `'view_notification'`
        * [x] For handling the click event, update the `onDismiss` callback function, calling the `trackEvent()` function and passing the following parameters: 
            * [x] `{viewContext}_kmw-settings-suggested-site-purpose-edit-notification`
            * [x] `confirm_notification`
 
* ### Tailored Metrics Suggestion Modal
* ![Image](https://github.com/user-attachments/assets/e1f5475d-09d5-4ba8-a6a7-ff2ecde72e76)
    * [x] Within the file at `assets/js/components/KeyMetrics/ConfirmSitePurposeChangeModal.js`:
        * [x] Import the `trackEvent` function as used to track internal events throughout the codebase
        * [x] For handling the primary CTA click event, update the existing `saveChanges` callback function, calling the `trackEvent()` function and passing the following parameters: 
            * [x] `{viewContext}_kmw-settings-tailored-metrics-suggestions`
            * [x] `'confirm_update_metrics_selection'`
        * [x] For handling the secondary CTA click event, update the existing `onClose` callback function, calling the `trackEvent()` function and passing the following parameters: 
            * [x] `{viewContext}_kmw-settings-tailored-metrics-suggestions`
            * [x] `'cancel_update_metrics_selection'`

* ### CTA Giving Existing Manual KMW Users The Option to Switch to Tailored
* ![Image](https://github.com/user-attachments/assets/47a0c7f1-d82b-4ebc-83c0-1185f111398f)
    * [x] Within the file at `assets/js/components/KeyMetrics/ConversionReportingSettingsSubtleNotification.js`:
        * [x] Import the `trackEvent` function as used to track internal events throughout the codebase
        * [x] For handling the CTA click event, update the existing `handleCTAClick` callback function, calling the `trackEvent()` function and passing the following parameters: 
            * [x] `{viewContext}_kmw-settings-change-from-manual-to-tailored`
            * [x] `'confirm_get_tailored_metrics'`
         * [x] For handling the `view_notification` event, an implementation of a `isViewed` state,  along with the user of `useIntersection` will be necessary:
            * [x] Use the file at `assets/js/components/notifications/BannerNotification/index.js` as a reference for how to implement the `isViewed` state, and use of `useIntersection`
            * [x] Implement the view state and use of `useIntersection` logic (i.e `.isIntersecting`) within a new `useEffect` hook,  if the component is in view and has not _yet_ been viewed, call the `trackEvent()` function and pass the following parameters:
                * [x] `{viewContext}_kmw-settings-change-from-manual-to-tailored`
                * [x] `'view_notification'`

* ### Extension of Existing `metrics_sidebar_save` Tracked Event
    * [x] Within the file at `assets/js/components/KeyMetrics/MetricsSelectionPanel/Footer.js`:
        * [x] Within the `onSaveSuccess` callback function where the existing `trackEvent` function is called: 
            * [x] Store the results of the `getUserPickedMetrics` selector from the `CORE_USER` datastore
            * [x] Store the results of the `getKeyMetricsConversionEventWidgets` selector from the `MODULES_ANALYTICS_4` datastore
            * [x] Check whether the arrays intersect, i.e if any of the user saved metrics as chosen in the sidebar are conversion reporting ones. Use `Object.keys()` on the result of `getKeyMetricsConversionEventWidgets` go get widget slugs only
            * [x] If there are no conversion reporting based metrics saved, leave the tracking as it currently is
            * [x] If there ARE conversion reporting based metrics saved, update the `trackEvent` call to include a `conversion_reporting` label

### Test Coverage

* Ensure that existing JS and VRT tests continue to pass

### Please ping @zutigrm for the latest version of the tester plugin containing the Analytics Conversion Tracking enhancements

- Set up Site Kit with GA4 connected and configure KMW in a manual state. Ensure that the GA4 account connected does not have conversion events, as we'll use the latest enhancements to the tester plugin to simulate events, new events and lost events. The simplest manner to do this, is to create a new account and property during setup.
    - Select 4 random KMW metrics as part of the manual setup
- Install and/or activate the [Tag Assistant Companion Chrome extension](https://chromewebstore.google.com/detail/tag-assistant-companion/jmekfmbnaedfebfnmakmokmlfpblbfdm?hl=en&pli=1)
- Enable the `conversionReporting` feature flag in site kit tester plugin
- Start Google Tag Assistant via the companion Chrome extension 

#### Testing initial events, new events and lost events with KMW manually set up
- For "initial events",  within the tester plugin, under the Analytics Conversion Reporting section, force the presence of one of the events, i.e `contact`
- Navigate to the main dashboard, and to the KMW section
- Validate that the new events banner is present
- Validate that the applicable tracking events are fired for the following scenarios:
    - `view_notification` event for when the banner/notice is seen
    - `confirm_select_new_conversion_metrics` for when the primary CTA is clicked 
    - `dismiss_notification` for when the notice is dismissed
- For "newly detected/additional events",  within the tester plugin, under the Analytics Conversion Reporting section, force the presence of one of the _NEW_ events, i.e  `add_to_cart`
- Navigate to the main dashboard, and to the KMW section
- Validate that the newly detected events banner is present
- Validate that the applicable tracking events are fired for the following scenarios:
    - `view_notification` event for when the banner/notice is seen
    - `confirm_view_new_conversion_metrics` for when the primary CTA is clicked 
    - `dismiss_notification` for when the notice is dismissed
- For "lost events",  within the tester plugin, under the Analytics Conversion Reporting section, force one of the existing events as lost, such as `add_to_cart`. Ensure that said event is also unchecked within the presence of events and new events sections of this tester section, i.e only the `add_to_cart` event should be checked in the lost events section
- Navigate to the main dashboard, and to the KMW section
- Validate that the lost events banner is present
- Validate that the applicable tracking events are fired for the following scenarios:
    - `view_notification` event for when the banner/notice is seen
    - `confirm_select_metrics ` for when the CTA is clicked 
    - `dismiss_notification` for when the notice is dismissed
 
#### Testing the CTA giving existing manual KMW users the option to switch to tailored
- With manual KMW set up, navigate to Site Kit > Settings > Admin > Key Metrics section
- Validate the presence of said banner and that the `view_notification` event is fired against said banner
- Validate the the `confirm_get_tailored_metrics` event fires when clicking on the CTA

#### Testing initial events, new events and lost events with _tailored_ KMW set up
- Reset Site Kit, follow the initial set instructions above but choose the _tailored_ setup route for KMW
- For "initial events",  within the tester plugin, under the Analytics Conversion Reporting section, force the presence of one of the events, i.e `contact`
- Navigate to the main dashboard, and to the KMW section
- Validate that the new events banner is present
- Validate that the applicable tracking events are fired for the following scenarios:
    - `view_notification` event for when the banner/notice is seen
    - `confirm_add_new_conversion_metrics ` for when the primary CTA is clicked 
    - `dismiss_notification` for when the notice is dismissed
- For "newly detected/additional events",  within the tester plugin, under the Analytics Conversion Reporting section, force the presence of one of the _NEW_ events, i.e  `add_to_cart`
- Navigate to the main dashboard, and to the KMW section
- Validate that the newly detected events banner is present
- Validate that the applicable tracking events are fired for the following scenarios:
    - `view_notification` event for when the banner/notice is seen
    - `confirm_view_new_conversion_metrics` for when the primary CTA is clicked 
    - `dismiss_notification` for when the notice is dismissed
- For "lost events",  within the tester plugin, under the Analytics Conversion Reporting section, force one of the existing events as lost, such as `add_to_cart`. Ensure that said event is also unchecked within the presence of events and new events sections of this tester section, i.e only the `add_to_cart` event should be checked in the lost events section
- Navigate to the main dashboard, and to the KMW section
- Validate that the lost events banner is present
- Validate that the applicable tracking events are fired for the following scenarios:
    - `view_notification` event for when the banner/notice is seen
    - `confirm_select_metrics ` for when the CTA is clicked 
    - `dismiss_notification` for when the notice is dismissed

#### Testing the tailored metrics suggestion modal
- With tailored KMW set up, navigate to `Site Kit > Settings > Admin > Key Metrics` section
- Edit the site purpose and change the answer 
- Validate the presence of the tailored metric suggestions modal
- Validate that the applicable tracking events are fired for the following scenarios:
    - When choosing to keep existing events, the `cancel_update_metrics_selection` event is fired
    - When updating the metrics selection, the `confirm_update_metrics_selection` event is fired  

#### Testing the banner encouraging existing user input users to edit purpose answer
- With a tailored KMW set up, choose the "Sell products" answer
- Within your database, navigate to `wp_options`, find the entry with the `option_name` value of `googlesitekit_user_input_settings`, and edit the value of `option_value`
- Update the text that reads as follows: `s:13:"sell_products"`
- Change it to the following: `s:24:"sell_products_or_service"`
- Reload the settings page
- validate the presence of the banner encouraging the user to update the site purpose answer
- Validate that the applicable tracking events are fired for the following scenarios:
    - `view_notification` when the notice is seen
    - `confirm_notification` when the CTA is clicked 

#### IMPORTANT: Handling Dismissal State
- Once either of the callout banners are dismissed, a database change needs to occur in order to reinstate the banners. Please reference the QAB for https://github.com/google/site-kit-wp/issues/9897 in order to ascertain how this is done.

## Changelog entry

* N/A

**Comment by zutigrm** [comment]
Thanks @10upsimon almost there. Let's clarify categories that will be used for tracking those elements, and include them on the tracking sheet. For banner we can follow the existing KMW categories/naming, for example like [these](https://docs.google.com/spreadsheets/d/1eEuJ2ppVZuai1_hL77RA2vL7DUidM_qCnvTsjxZ_S4k/edit?gid=925918307#gid=925918307&range=305:307)

**Comment by 10upsimon** [comment]
Thanks @zutigrm I think in general, due to there being a bunch more CTA's and/or banners etc introduced as part of this epic, this needs a bit of reorganisation. 

I'll define some categories and labels, add them to the tracking sheet and review with @marrrmarrr

**Comment by zutigrm** [comment]
Thanks @10upsimon  AC ✅ 

I sorted few copy-paste mix ups in AC and sheet

**Comment by wpdarren** [comment]
### QA Update: ✅ 

I have made the decision to move this to approval.  I will be testing this on Monday as part of the ACR bug bashing and it's behind a feature flag so is not user facing.
