### ISSUE TITLE
Add GA event tracking for the Setup CTA Banner, including events which are shared with the Settings setup process

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#9493]
## Feature Description

GA events should be added to keep track of interaction with the Setup CTA Banner. Some events will be shared with the setup flow on the Settings screen.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

The following GA events should be tracked for the given actions. See the [GA events sheet](https://docs.google.com/spreadsheets/d/1eEuJ2ppVZuai1_hL77RA2vL7DUidM_qCnvTsjxZ_S4k/edit?gid=925918307#gid=925918307&range=385:402).

Event Name | Category | Trigger | Condition | Description/details
-- | -- | -- | -- | --
view_notification | {viewContext}_audiences-setup-cta-dashboard | Element visibility | User views the [Audience Segmentation Setup CTA notification](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1956-17850&node-type=frame&t=PJX3Y7OESgwokk2d-0) on the dashboard
confirm_notification | {viewContext}_audiences-setup-cta-dashboard | Click | User clicks "Enable groups" on the notification
dismiss_notification | {viewContext}_audiences-setup-cta-dashboard | Click | User clicks "Maybe later" on the notification
tooltip_view | {viewContext}_audiences-setup-cta-dashboard | Element visibility | User views the [tooltip that appears when dismissing the notification](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1834-32286&node-type=frame&t=PNTGwXm0OYTItlYB-0)  | Event named for consistency with the corresponding event for KMW
tooltip_dismiss | {viewContext}_audiences-setup-cta-dashboard | Click | User clicks "Got it" on the tooltip | As above
view_notification | {viewContext}_setup-success-notification-audiences | Element visibility  | User views the [Audience Segmentation Setup Success notification](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1415-15958&node-type=frame&t=PJX3Y7OESgwokk2d-0) on the dashboard | The category for this component is aligned with the conventions for the new notifications infrastructure, and the events should already be implemented as a result of the component migration specced in GH #9281
confirm_notification | {viewContext}_setup-success-notification-audiences | Click | User clicks "Show me" on the notification
dismiss_notification | {viewContext}_setup-success-notification-audiences | Click | User clicks "Got it" on the notification
auth_error | {viewContext}_audiences-setup | Element visibility  | User views the [OAuth error modal](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1890-23488&node-type=frame&t=PJX3Y7OESgwokk2d-0) on the dashboard or Settings screen when an error occurs during setup
auth_error_retry | {viewContext}_audiences-setup | Click | User clicks "Retry" on the modal
auth_error_cancel | {viewContext}_audiences-setup | Click | User clicks "Cancel" on the modal
insufficient_permissions_error | {viewContext}_audiences-setup | Element visibility  | User views the [insufficient permissions error modal](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1890-23292&node-type=frame&t=PJX3Y7OESgwokk2d-0) on the dashboard or Settings screen during setup
insufficient_permissions_error_request_access | {viewContext}_audiences-setup | Click | User clicks "Request access" on the modal
insufficient_permissions_error_cancel | {viewContext}_audiences-setup | Click | User clicks "Cancel" on the modal
setup_error | {viewContext}_audiences-setup | Element visibility  | User views the [generic error modal](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1890-23073&node-type=frame&t=PJX3Y7OESgwokk2d-0) on the dashboard or Settings screen when an error occurs during setup
setup_error_retry | {viewContext}_audiences-setup | Click | User clicks "Retry" on the modal
setup_error_cancel | {viewContext}_audiences-setup | Click | User clicks "Cancel" on the modal

## Implementation Brief

- [ ] Refactor the [`AudienceSegmentationSetupCTAWidget`](https://github.com/google/site-kit-wp/blob/8a891c49d336264431477571d21bca63ebf09f9b/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSegmentationSetupCTAWidget.js) component to be a module with its own folder and an `index.js` file.
- [ ] Extract the [main JSX content](https://github.com/google/site-kit-wp/blob/9924efe437dd4c30f85916214b63fe30865f23a1/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSegmentationSetupCTAWidget.js#L219-L318) from the `AudienceSegmentationSetupCTAWidget` component to a new component e.g. `SetupCTAContent`.
  - Wrap the `SetupCTAContent` component in `forwardRef()` so a `ref` can be passed to it, and add the `ref` to its top-level rendered element.
- [ ] In the `AudienceSegmentationSetupCTAWidget` component:
  - Create a version of `SetupCTAContent` wrapped by the `withIntersectionObserver()` HOC, e.g. `SetupCTAContentWithIntersectionObserver`. Render this in place of the existing `SetupCTAContent` instance.
  - Pass the `onInView` callback prop to `SetupCTAContentWithIntersectionObserver`. In the callback, call `trackEvent( '${viewContext}_audiences-setup-cta-dashboard', 'view_notification' )`.
  - Create a `handleEnableGroups()` callback:
    - Call `trackEvent( '${viewContext}_audiences-setup-cta-dashboard', 'confirm_notification' )`, followed by `onEnableGroups()`. Chain the two calls using `.finally()`.
  - Replace `onEnableGroups` with `handleEnableGroups` as the value for the `onClick` prop that is passed to `SpinnerButton`.
  - Amend the `handleDismissClick()` callback:
    - Call `trackEvent( '${viewContext}_audiences-setup-cta-dashboard', 'dismiss_notification' )` prior to the block where `dismissPrompt()` is called. Chain the call & code block using `.finally()`.
  - Add a `useEffect()` hook:
    - If `isTooltipVisible` is true, call `trackEvent( '${viewContext}_audiences-setup-cta-dashboard', 'tooltip_view' )`.
  - Pass the `onDismiss` callback prop to `AdminMenuTooltip`. In the callback, call `trackEvent( '${viewContext}_audiences-setup-cta-dashboard', 'tooltip_dismiss' )`.
  - Pass the `trackEventCategory` prop (see https://github.com/google/site-kit-wp/issues/9495) to `AudienceErrorModal` with the value `${viewContext}_audiences-setup`.
- [ ] In the [`SettingsCardVisitorGroups/SetupCTA`](https://github.com/google/site-kit-wp/blob/8a891c49d336264431477571d21bca63ebf09f9b/assets/js/modules/analytics-4/components/audience-segmentation/settings/SettingsCardVisitorGroups/SetupCTA.js) component:
  - Pass the `trackEventCategory` prop to `AudienceErrorModal` with the value `${viewContext}_audiences-setup`.

Note that the events with category `{viewContext}_setup-success-notification-audiences` were implemented via https://github.com/google/site-kit-wp/issues/9281, and the logic for the events with category `{viewContext}_audiences-setup` will have been implemented via https://github.com/google/site-kit-wp/issues/9495, with only the category itself needing to be passed into `AudienceErrorModal` in this issue. We should still test all of the listed events in QA.

### Test Coverage

* Add JS test coverage for the above changes where tests exist for the affected components.
* The `auth_error`, `insufficient_permissions_error` and `setup_error` GA events can be excluded from the coverage as discussed here under **Relevant technical choices**: https://github.com/google/site-kit-wp/pull/9542#issue-2603337565

## QA Brief

- As a prerequisite for testing the events for each scenario:
  - Have a mechanism for checking tracked Analytics events ready, e.g. Tag Assistant or the Google Analytics Debugger Chrome extension.
  - Set up Site Kit with the `audienceSegmentation` feature flag enabled, tracking enabled, and Analytics connected using a property which is out of the gathering data state.

### CTA events

- When the Setup CTA Banner appears, verify the `view_notification` event with category `{viewContext}_audiences-setup-cta-dashboard` is tracked as per the AC.
- Click on **Enable groups** to set up Audience Segmentation.
- Verify the `confirm_notification` event with category `{viewContext}_audiences-setup-cta-dashboard` is tracked as per the AC.
- Cancel out of the OAuth flow, and close the OAuth error modal to return to the Audience Segmentation Setup CTA.
- This time, click on **Maybe later** to dismiss the CTA.
- Verify the `dismiss_notification` event with category `{viewContext}_audiences-setup-cta-dashboard` is tracked as per the AC.
- The Settings tooltip should appear. Verify the `tooltip_view` event is tracked as per the AC.
- Close the tooltip. Verify the `tooltip_dismiss` event is tracked as per the AC.

### Success notification events

- Set up Site Kit again and click on **Enable groups** to set up Audience Segmentation.
- Upon setting up Audience Segmentation, the success notification should appear.
- Verify the `view_notification` event with category `{viewContext}_setup-success-notification-audiences` is tracked as per the AC.
- Click on **Show me** on the notification.
- Verify the `confirm_notification` event with category `{viewContext}_setup-success-notification-audiences` is tracked as per the AC.
- Set up Site Kit again and click on **Enable groups** to set up Audience Segmentation.
- Click on **Got it** to dismiss the success notification.
- Verify the `dismiss_notification` event with category `{viewContext}_setup-success-notification-audiences` is tracked as per the AC.

#### OAuth error

- Set up Site Kit again and click on **Enable groups** to set up Audience Segmentation.
- Cancel out of the OAuth flow to return to Site Kit with an OAuth error.
- Verify the `auth_error` event is tracked as per the AC.
- Click **Retry** on the error modal and verify the `auth_error_retry` event is tracked as per the AC.
- Cancel the OAuth flow again to re-show the error modal. Click **Cancel** on the modal and verify the `auth_error_cancel` event is tracked as per the AC.

#### Insufficient permissions error

- Set up Site Kit again.
- Either remove view access to the connected GA property, or simulate the insufficient permissions error using the following Tweak Chrome extension configuration:
  - URL: `.*/wp-json/google-site-kit/v1/modules/analytics-4/data/sync-audiences.*`
  - Enable the use of regular expression `(.*)`
  - HTTP Method: `POST`
  - Status code: `403`
  - Response payload:
    ```json
    {
      "code": 403,
      "message": "Insufficient Permissions Test Error",
      "data": {
        "status": 403,
        "reason": "insufficientPermissions"
      }
    }
    ```
- Click on **Enable groups** to set up Audience Segmentation and proceed through the OAuth flow.
- Upon returning to Site Kit the error modal should appear showing the insufficient permissions error message.
- Verify the `insufficient_permissions_error` event is tracked as per the AC.
- Click **Request access** on the modal and verify the `insufficient_permissions_error_request_access` event is tracked as per the AC.
- Click **Cancel** on the modal and verify the `insufficient_permissions_error_request_cancel` event is tracked as per the AC.

#### Generic error

- Set up Site Kit again.
- Simulate an API error other than the insufficient permissions error, for example a 500 error using the following Tweak configuration:
  - URL: `.*/wp-json/google-site-kit/v1/modules/analytics-4/data/sync-audiences.*`
  - Enable the use of regular expression `(.*)`
  - HTTP Method: `POST`
  - Status code: `500`
  - Response payload:
    ```json
    {
      "code": "internal_server_error",
      "message": "Internal server error",
      "data": {
        "status": 500
      }
    }
    ```
- Click on **Enable groups** to set up Audience Segmentation and proceed through the OAuth flow.
- Upon returning to Site Kit the error modal should appear showing the generic error message.
- Verify the `setup_error` event is tracked as per the AC.
- Click **Retry** on the modal and verify the `setup_error_retry` event is tracked as per the AC.
- Click **Cancel** on the modal and verify the `setup_error_request_cancel` event is tracked as per the AC.

## Changelog entry

* Add opt-in user activity tracking in the audience setup CTA widget and related setting areas.

**Comment by nfmohit** [comment]
IB ✅

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Tested this and all the events are firing as expected.
Moving ticket to approval.

- view_notification
   <Details>

   ![Image](https://github.com/user-attachments/assets/b178611a-dcd3-4fc0-9017-e5a2e71e75b4)

   </Details>
- confirm_notification
   <Details>

   ![Image](https://github.com/user-attachments/assets/9007fc10-98af-4cce-b825-698ad4a11495)
   
   </Details>
- dismiss_notification
   <Details>

   ![Image](https://github.com/user-attachments/assets/29f49ef3-ba98-4e07-aee9-518f21623612)
   
   </Details>
- tooltip_view
   <Details>

   ![Image](https://github.com/user-attachments/assets/87dba63f-7d60-41c9-882b-0382e4160415)

   </Details>
- tooltip_dismiss
   <Details>

   ![Image](https://github.com/user-attachments/assets/c77d5b83-ec8a-46ba-8b2e-2d2ea7d5a2fd)

   </Details>
- view_notification
   <Details>

   ![Image](https://github.com/user-attachments/assets/53ac65a7-6f52-4842-a6da-8869bb019a73)

   </Details>
- confirm_notification
   <Details>

   ![Image](https://github.com/user-attachments/assets/0a41d500-1e0d-4530-bbc0-37dde48474ca)

   </Details> 
- dismiss_notification
   <Details>

   ![Image](https://github.com/user-attachments/assets/97444bef-078e-4832-a963-2ef6bf42f96a)

   </Details> 
- auth_error
   <Details>

   ![Image](https://github.com/user-attachments/assets/27b2dd1d-8eb8-4800-9cc4-f00aae809547)

   </Details>
- auth_error_retry
   <Details>

   ![Image](https://github.com/user-attachments/assets/60ec8293-8119-44b6-b464-6f9fff98229f)

   </Details>
- auth_error_cancel
   <Details>

   ![Image](https://github.com/user-attachments/assets/55341d32-dcd6-4282-97e3-afd88d18388c)

   </Details>
- insufficient_permissions_error
   <Details>

   ![Image](https://github.com/user-attachments/assets/3ba62d99-9eb3-4323-b97d-e5968742c095)

   </Details>
- insufficient_permissions_error_request_access
   <Details>

   ![Image](https://github.com/user-attachments/assets/e4408dbe-7f66-4593-87e5-067d267150f9)

   </Details>
- insufficient_permissions_error_cancel
   <Details>

   ![Image](https://github.com/user-attachments/assets/8b2e0dbc-80d0-4033-b788-04ea2c8c319a)

   </Details>
- setup_error
   <Details>

   ![Image](https://github.com/user-attachments/assets/b82f96f1-845d-450c-9cf5-65112e8bcda1)

   </Details>
- setup_error_retry
   <Details>

   ![Image](https://github.com/user-attachments/assets/01551ed6-5f5f-408d-85f1-905d0928fb1b)

   </Details>
- setup_error_cancel
   <Details>

   ![Image](https://github.com/user-attachments/assets/369a197f-b745-4d67-b3dd-8ddd3dc0be00)

   </Details>
