### ISSUE TITLE
Add GA event tracking for the Audiences Tiles (excluding the "Top content" metric area)

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#9494]
## Feature Description

GA events should be added to keep track of interaction with Audience Tiles (barring the "Top content" metric area which will be addressed separately).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

The following GA events should be tracked for the given actions. See the [GA events sheet](https://docs.google.com/spreadsheets/d/1eEuJ2ppVZuai1_hL77RA2vL7DUidM_qCnvTsjxZ_S4k/edit?gid=925918307#gid=925918307&range=403:415).

Event Name | Category | Label | Trigger | Condition
-- | -- | -- | -- | --
insufficient_permissions_error | {viewContext}_audiences-tile | one of "new-visitors", "returning-visitors", "purchasers", "all-users", or empty | Element visibility  | User views an [insufficient permissions audience tile error](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=3395-16686&node-type=frame&t=PJX3Y7OESgwokk2d-0)
insufficient_permissions_error_request_access | {viewContext}_audiences-tile | one of "new-visitors", "returning-visitors", "purchasers", "all-users", or empty | Click | User clicks "Request access" on the error
data_loading_error | {viewContext}_audiences-tile | one of "new-visitors", "returning-visitors", "purchasers", "all-users", or empty | Element visibility  | User views a [generic audience tile error](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1396-25492&node-type=frame&t=PJX3Y7OESgwokk2d-0)
data_loading_error_retry | {viewContext}_audiences-tile | one of "new-visitors", "returning-visitors", "purchasers", "all-users", or empty | Click | User clicks "Retry" on the error
view_tile_tooltip | {viewContext}_audiences-tile | one of "new-visitors", "returning-visitors", "purchasers", "all-users", or empty | click/hover | User views the [tooltip for an audience tile](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1050-56092&node-type=frame&t=PNTGwXm0OYTItlYB-0)
view_tile_partial_data_tooltip | {viewContext}_audiences-tile | one of "purchasers", "all-users", or empty | click/hover | User views the [tooltip for a partial data badge for an audience tile](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=2059-32538&node-type=frame&t=PNTGwXm0OYTItlYB-0)
view_top_content_partial_data_tooltip | {viewContext}_audiences-tile | one of "new-visitors", "returning-visitors", "purchasers", "all-users", or empty | click/hover | User views the [tooltip for a partial data badge in the "Top content" area of an audience tile](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=3155-16408&node-type=frame&t=PNTGwXm0OYTItlYB-0)
view_tile_collecting_data | {viewContext}_audiences-tile | one of "new-visitors", "returning-visitors", "purchasers", "all-users", or empty | Element visibility  | User views the ["collecting data" tile variant](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1046-43397&node-type=frame&t=PJX3Y7OESgwokk2d-0) for an audience tile
temporarily_hide | {viewContext}_audiences-tile | one of "new-visitors", "returning-visitors", "purchasers", "all-users", or empty | Click | User clicks "temporarily hide" on the tile
insufficient_permissions_error | {viewContext}_audiences-all-tiles |  | Element visibility  | User views the [insufficient permissions full width error](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=2389-25123&node-type=frame&t=PJX3Y7OESgwokk2d-0)
insufficient_permissions_error_request_access | {viewContext}_audiences-all-tiles |  | Click | User clicks "Request access" on the error
data_loading_error | {viewContext}_audiences-all-tiles |  | Element visibility  | User views the [generic full width error](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=2258-36170&node-type=frame&t=PJX3Y7OESgwokk2d-0)
data_loading_error_retry | {viewContext}_audiences-all-tiles |  | Click | User clicks "Retry" on the error

## Implementation Brief

- [ ] Refactor the [`AudienceTileError`](https://github.com/google/site-kit-wp/blob/fbcf92fbcedd4e71b158282692cf13ce780ed863/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTile/AudienceTileError.js) component to be a module with its own folder and an `index.js` file.
- [ ] Extract the [rendered JSX content](https://github.com/google/site-kit-wp/blob/3ac038e5867c9c209ffe3873f41c2e80fc4cbfb6/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTile/AudienceTileError.js#L43-L77) from the `AudienceTileError` component to a new component e.g. `TileErrorContent`.
  - Wrap the `TileErrorContent` component in `forwardRef()` so a `ref` can be passed to it, and add the `ref` to its top-level rendered element.
  - Add an `onRetry` prop of type `PropTypes.func` to `TileErrorContent`, and pass it through to `ReportErrorActions`.
- [ ] In the `AudienceTileError` component:
  - Add an `audienceSlug` prop of type `PropTypes.string`.
  - Create a version of `TileErrorContent` wrapped by the `withIntersectionObserver()` HOC, e.g. `TileErrorContentWithIntersectionObserver`. Render this in place of the existing `TileErrorContent` instance.
  - Pass the `onInView` callback prop to `TileErrorContentWithIntersectionObserver`:
    - Determine the action for the GA event: `insufficient_permissions_error` for an insufficient permissions error, or `data_loading_error` for any other error.
    - Call `trackEvent( '${viewContext}_audiences-tile', action, audienceSlug )`.
  - Pass the `onRetry` callback prop to `TileErrorContent`:
    - Determine the action for the GA event: `insufficient_permissions_error_request_access` for an insufficient permissions error, or `data_loading_error_retry` for any other error.
    - Call `trackEvent( '${viewContext}_audiences-tile', action, audienceSlug )`.
- [ ] Add an `onOpen` prop of type `PropTypes.func` to both the [`InfoTooltip`](https://github.com/google/site-kit-wp/blob/fbcf92fbcedd4e71b158282692cf13ce780ed863/assets/js/components/InfoTooltip.js) and [`Tooltip`](https://github.com/google/site-kit-wp/blob/fbcf92fbcedd4e71b158282692cf13ce780ed863/assets/js/googlesitekit/components-gm2/Tooltip.js) components. Pass the prop through from `InfoTooltip` to `Tooltip` to `MuiTooltip`.
- [ ] Add an `onTooltipOpen` prop of type `PropTypes.func` to the [`BadgeWithTooltip`](https://github.com/google/site-kit-wp/blob/fbcf92fbcedd4e71b158282692cf13ce780ed863/assets/js/components/BadgeWithTooltip.js) component. Pass the prop through as the `onOpen` prop to `InfoTooltip`.
- [ ] In the [`AudienceTile`](https://github.com/google/site-kit-wp/blob/fbcf92fbcedd4e71b158282692cf13ce780ed863/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTile/index.js) component:
  - Add an `audienceSlug` prop of type `PropTypes.string` and pass it through to the [`AudienceTilePagesMetric`](https://github.com/google/site-kit-wp/blob/fbcf92fbcedd4e71b158282692cf13ce780ed863/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTile/AudienceTilePagesMetric.js) component.
  - Pass the `onOpen` callback prop to `InfoTooltip`. In the callback, call `trackEvent( '${viewContext}_audiences-tile', 'view_tile_tooltip', audienceSlug )`.
  - Pass the `onTooltipOpen` callback prop to `BadgeWithTooltip`. In the callback, call `trackEvent( '${viewContext}_audiences-tile', 'view_tile_partial_data_tooltip', audienceSlug )`.
- [ ] In the `AudienceTilePagesMetric` component:
  - Add an `audienceSlug` prop of type `PropTypes.string`.
  - Pass the `onTooltipOpen` callback prop to `BadgeWithTooltip`. In the callback, call `trackEvent( '${viewContext}_audiences-tile', 'view_top_content_partial_data_tooltip', audienceSlug )`.
- [ ] In the `AudienceTiles` component:
  - Pass the `audienceSlug` prop to the `AudienceTile` and `AudienceTileError` components with the value of the `audienceSlug` constant.
- [ ] Create a new `AudienceTileZeroData` component. Make `AudienceTileZeroData` a module with its own `index.js` file and create another component, `TileZeroDataContent` in the module folder.
- [ ] Extract the [JSX content for the zero-data tile variant](https://github.com/google/site-kit-wp/blob/fbcf92fbcedd4e71b158282692cf13ce780ed863/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTile/index.js#L140-L166) from the `AudienceTile` component to the new `TileZeroDataContent` component.
  - Wrap the `TileZeroDataContent` component in `forwardRef()` so a `ref` can be passed to it, and add the `ref` to its top-level rendered element.
- [ ] In the `AudienceTileZeroData` component:
  - Add an `audienceSlug` prop of type `PropTypes.string`.
  - Create a version of `TileZeroDataContent` wrapped by the `withIntersectionObserver()` HOC, e.g. `TileZeroDataContentWithIntersectionObserver`. Render the `TileZeroDataContentWithIntersectionObserver` component.
  - Pass the `onInView` callback prop to `TileZeroDataContentWithIntersectionObserver`. In the callback, call `trackEvent( '${viewContext}_audiences-tile', 'view_tile_collecting_data', audienceSlug )`.
  - Create a `handleHideTile()` callback:
    - Call `trackEvent( '${viewContext}_audiences-tile', 'temporarily_hide', audienceSlug )`, followed by `onHideTile()`. Chain the two calls using `.finally()`.
  - Replace `onHideTile` with `handleHideTile` as the value for the `onHideTile` prop that is passed to `TileZeroDataContentWithIntersectionObserver`.
- [ ] Refactor the [`AudienceSegmentationErrorWidget`](https://github.com/google/site-kit-wp/blob/fbcf92fbcedd4e71b158282692cf13ce780ed863/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSegmentationErrorWidget.js) component to be a module with its own folder and an `index.js` file.
- [ ] Extract the [rendered JSX content](https://github.com/google/site-kit-wp/blob/fbcf92fbcedd4e71b158282692cf13ce780ed863/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSegmentationErrorWidget.js#L76-L149) from the `AudienceSegmentationErrorWidget` component to a new component e.g. `ErrorWidgetContent`.
  - Wrap the `ErrorWidgetContent` component in `forwardRef()` so a `ref` can be passed to it, and add the `ref` to its top-level rendered element.
- [ ] In the `AudienceSegmentationErrorWidget` component:
  - Create a version of `ErrorWidgetContent` wrapped by the `withIntersectionObserver()` HOC, e.g. `ErrorWidgetContentWithIntersectionObserver`. Render this in place of the existing `ErrorWidgetContent` instance.
  - Pass the `onInView` callback prop to `ErrorWidgetContentWithIntersectionObserver`:
    - Determine the action for the GA event: `insufficient_permissions_error` for an insufficient permissions error, or `data_loading_error` for any other error.
    - Call `trackEvent( '${viewContext}_audiences-all-tiles', action )`.
  - Amend the `handleRetry()` callback:
    - Determine the action for the GA event: `insufficient_permissions_error_request_access` for an insufficient permissions error, or `data_loading_error_retry` for any other error.
    - Call `trackEvent( '${viewContext}_audiences-all-tiles', action )` prior to the calls to `setValue()` and `onRetry()`. Chain the calls using `trackEvent().finally()`.

### Test Coverage

* Add JS test coverage for the above changes where tests exist for the affected components.

## QA Brief

- As a prerequisite for testing the events for each scenario:
  - Have a mechanism for checking tracked Analytics events ready, e.g. Tag Assistant or the Google Analytics Debugger Chrome extension.
  - Set up Site Kit with the `audienceSegmentation` feature flag enabled, tracking enabled, and Analytics connected using a property which is out of the gathering data state.
  - Click on **Enable groups** to set the feature up.

### Error events

- Follow the QAB for https://github.com/google/site-kit-wp/issues/8147 to show the generic audience tile error and the generic full width error.
- Verify the `data_loading_error` event is tracked as per the AC for each of the error cases.
- Click on **Retry** for each case and verify the `data_loading_error_retry` event is tracked as per the AC.
- Follow the QAB for #8147 again, but change the status code to `403` and the response payload to the following to show the insufficient permissions audience tile error and the insufficient permissions full width error.

```json
{
  "code": 403,
  "message": "Insufficient Permissions Test Error",
  "data": {
    "status": 403,
    "reason": "insufficientPermissions"
  }
}
```

- Verify the `insufficient_permissions_error` event is tracked as per the AC for each of the error cases.
- Click on **Request access** for each case and verify the `insufficient_permissions_error_request_access` event is tracked as per the AC.

### Tooltip events

- Click/hover the info icon by the title of an audience tile and verify the `view_tile_tooltip` event is tracked as per the AC.
- Using a property with an audience in the partial data state, click/hover the info icon in the "partial data" badge at the top of an audience tile and verify the `view_tile_partial_data_tooltip` event is tracked as per the AC.
- Using a property with a custom dimension audience in the partial data state, click/hover the info icon in the "partial data" badge in the "Top content" metric area of an audience tile and verify the `view_top_content_partial_data_tooltip` event is tracked as per the AC.

### "Collecting data" events

- Using a property with an audience in the partial data state, and zero data for the audience, verify the `view_tile_collecting_data` event is tracked when the "Site Kit is collecting data for this group." tile variant is shown as per the AC.
- Click on **Temporarily hide** for the audience and verify the `temporarily_hide` event is tracked as per the AC.

## Changelog entry

* Add opt-in user activity tracking in the audience tiles area.

**Comment by nfmohit** [comment]
IB ✅

**Comment by kelvinballoo** [comment]
### QA Update ⚠ 

Couple of questions:

**ITEM 1:**
From the AC, for `{viewContext}_audiences-tile	view_tile_partial_data_tooltip`, is it still valid?
From https://github.com/google/site-kit-wp/issues/8144#event-14208851247, it feels like Partial Data badge has been removed.
Unless I am wrong, could you add the steps to simulate this please?
______________________________________________________________________________

**ITEM 2:**
Per the AC, one of the labels mentioned is "publishers".
Could you clarify when "publishers" would appear as the label?
From my testing, I had "purchasers" instead whenever I use the 'Purchasers' tiles.

**Comment by techanvil** [comment]
Hi @kelvinballoo! To answer your q's:

- Item 1: The partial data badge is still relevant and will be shown for audiences other than the "new visitors" and "returning visitors" audiences as we treat them as a special case as discussed in #8144. So, in order to show the partial data badge and test this case, use the default or user-defined audiences. The label in the AC should not have included the "new-visitors" and "returning-visitors" values, this was an oversight and I've amended it to removed them.
- Item 2: This was a typo and it should have been "purchasers", I've amended this too in the AC. Thanks for spotting these, sorry for the confusion!
