### ISSUE TITLE
Add GA event tracking for the No Audiences Banner and Info Notice

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#9496]
## Feature Description

GA events should be added to keep track of interaction with the No Audiences Banner and Info Notice.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

The following GA events should be tracked for the given actions. See the [GA events sheet](https://docs.google.com/spreadsheets/d/1eEuJ2ppVZuai1_hL77RA2vL7DUidM_qCnvTsjxZ_S4k/edit?gid=925918307#gid=925918307&range=427:431).

Event Name | Category | Label | Trigger | Condition | Description/details
-- | -- | -- | -- | -- | --
view_banner | {viewContext}_audiences-no-audiences | one of "none-selected" or "no-longer-available" | Element visibility  | User views the "no audiences" banner | none-selected: The user views [the variant where they have never had a populated selection](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=2602-21140&node-type=frame&t=PJX3Y7OESgwokk2d-0)<br/>no-longer-available: The user views [the variant where their previous selection is not longer available](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1399-11690&node-type=frame&t=PJX3Y7OESgwokk2d-0)
select_groups | {viewContext}_audiences-no-audiences | one of "none-selected" or "no-longer-available" | Click | User clicks the "Select groups" or "Select other groups" CTA on the banner
change_settings | {viewContext}_audiences-no-audiences | one of "none-selected" or "no-longer-available" | Click | User clicks the link on the banner to navigate to Settings
view_notice | {viewContext}_audiences-info-notice | one of "new-visitors", "compare-metrics", "custom-audiences", "purchasers", "returning-visitors", "compare-new-returning", "compare-cities" | Element visibility  | User views a message in the [Info Notice](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1047-54324&node-type=frame&t=PNTGwXm0OYTItlYB-0) that appears below the audience tiles | These slugs represent the various [messages](https://github.com/google/site-kit-wp/blob/86903ca8aac8bbab50e55cc45075cd06808cd623/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/InfoNoticeWidget/constants.js#L48-L75)  that will be shown in the info notice
dismiss_notice | {viewContext}_audiences-info-notice | one of "new-visitors", "compare-metrics", "custom-audiences", "purchasers", "returning-visitors", "compare-new-returning", "compare-cities" | Click | User clicks "Got it" on the notice

## Implementation Brief

- [x] Wrap the [`NoAudienceBanner`](https://github.com/google/site-kit-wp/blob/6c26e3fc9cbbe8504bf201027b53326541aa31f4/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/NoAudienceBannerWidget/NoAudienceBanner.js) component in `forwardRef()` so a `ref` can be passed to it, and add the `ref` to its top-level rendered element.
- [x] In the [`NoAudienceBannerWidget`](https://github.com/google/site-kit-wp/blob/6c26e3fc9cbbe8504bf201027b53326541aa31f4/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/NoAudienceBannerWidget/index.js) component:
  - Create a version of `NoAudienceBanner` wrapped by the `withIntersectionObserver()` HOC, e.g. `NoAudienceBannerWithIntersectionObserver`. Render this in place of the existing `NoAudienceBanner` instance.
  - Determine the `label` for the GA event: `no-longer-available` when `didSetAudiences` is true, otherwise `none-selected`.
  - Add an `onInView` callback prop to `NoAudienceBannerWithIntersectionObserver`. In the callback, call `trackEvent( '${viewContext}_audiences-no-audiences', 'view_banner', label )`.
- [x] In the `NoAudienceBanner` component:
  - Determine the `label` for the GA event: `no-longer-available` when `didSetAudiences` is true, otherwise `none-selected`.
  - Amend the `onClick` handlers for the "Select groups" / "Select other groups" `Link` instances:
    - Call `trackEvent( '${viewContext}_audiences-no-audiences', 'select_groups', label )` prior to the call to `setValue`. Chain the two calls using `.finally()`.
  - Amend the `onClick` handler for the "You can deactivate this widget in Settings" `Link` instance:
    - Call `trackEvent( '${viewContext}_audiences-no-audiences', 'change_settings', label )` prior to the call to `navigateTo`. Chain the two calls using `.finally()`.
- [x] Wrap the [`InfoNotice`](https://github.com/google/site-kit-wp/blob/6c26e3fc9cbbe8504bf201027b53326541aa31f4/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/InfoNotice.js) component in `forwardRef()` so a `ref` can be passed to it, and add the `ref` to its top-level rendered element.
- [x] In the [`InfoNoticeWidget`](https://github.com/google/site-kit-wp/blob/6c26e3fc9cbbe8504bf201027b53326541aa31f4/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/InfoNoticeWidget/index.js) component:
  - Create a version of `InfoNotice` wrapped by the `withIntersectionObserver()` HOC, e.g. `InfoNoticeWithIntersectionObserver`. Render this in place of the existing `InfoNotice` instance.
  - Determine the `label` for the GA events: one of `new-visitors`, `compare-metrics`, `custom-audiences`, `purchasers`, `returning-visitors`, `compare-new-returning`, or `compare-cities`, depending on the current notice to be displayed.
  - Add an `onInView` callback prop to `InfoNoticeWithIntersectionObserver`. In the callback, call `trackEvent( '${viewContext}_audiences-info-notice', 'view_notice', label )`.
  - Amend the `onDismiss()` callback:
    - Call `trackEvent( '${viewContext}_audiences-info-notice', 'dismiss_notice', label )` prior to the call to `dismissPrompt`. Chain the two calls using `.finally()`.
- [x] Update the JSDoc for [`withIntersectionObserver()`](https://github.com/google/site-kit-wp/blob/6c26e3fc9cbbe8504bf201027b53326541aa31f4/assets/js/util/withIntersectionObserver.js) to remove the point about removing the hook when `useIntersection()` has been replaced. The HOC is a useful abstraction around a common pattern of `useIntersection()` usage that we can keep for the longer term.

### Test Coverage

* Add coverage for the above changes to the tests for `NoAudienceBanner` and `NoAudienceBannerWidget`.

## QA Brief

- As a prerequisite for testing the events for each component:
  - Have a mechanism for checking tracked Analytics events ready, e.g. Tag Assistant or the Google Analytics Debugger Chrome extension.
  - Set up Site Kit with the `audienceSegmentation` feature flag enabled, tracking enabled, and Analytics connected using a property which is out of the gathering data state.
  - Click on **Enable groups** to set the feature up.

### No Audiences Banner

- Events with the `no-longer-available` label:
  - Archive all of the audiences for the connected property barring "All Users".
  - Refresh the Site Kit dashboard and open the Audience Selection Panel to trigger a resync of the available audiences.
  - The No Audiences Banner should appear, showing the "It looks like your visitor groups aren’t available anymore" message.
  - Verify the `view_banner` event is tracked with the label `no-longer-available` as per the AC.
  - Click on **Select other groups** in the banner.
  - Verify the `select_groups` event is tracked with the label `no-longer-available` as per the AC.
  - Click on **Settings** in the banner.
  - Verify the `change_settings` event is tracked with the label `no-longer-available` as per the AC.
- Events with `none-selected` label:
  - Continuing with the flow above, login as a second admin user and connect Site Kit. The second admin should have view access or higher for the connected property.
  - The No Audiences Banner should appear, showing the "You don’t have any visitor groups selected" message.
  - Verify the `view_banner` event is tracked with the label `none-selected` as per the AC.
  - Click on **Select groups** in the banner.
  - Verify the `select_groups` event is tracked with the label `none-selected` as per the AC.
  - Click on **Settings** in the banner.
  - Verify the `change_settings` event is tracked with the label `none-selected` as per the AC.

### Info Notice

- Follow the QAB for https://github.com/google/site-kit-wp/issues/8139, repeating point 9 with the values of `0` to `6` inclusive for `count` in order to iterate through the sequence of Info Notice messages:

> 9. Once a notice is dismissed, it takes two weeks for the next notice to appear. To be able to see any notice immediately, try the following script in the browser console:
> ```js
> googlesitekit.data.dispatch('core/user').receiveGetDismissedPrompts( {
>     'audience-segmentation-info-notice': {
>         expires: Math.floor( Date.now() / 1000 ) - 10,
>         count: 0 // Change this to any number of notice that you intend to see (0 - 6).
>     }
> } );
> ```

- Each time a message is shown:
  - Verify the `view_notice` event is tracked with the correct label as per the AC.
  - Click on **Got it** in the notice and verify the `dismiss_notice` event is tracked with the correct label as per the AC.

## Changelog entry

* Add GA event tracking for user interactions with the No Audiences Banner and Info Notice.

**Comment by nfmohit** [comment]
Thank you for drafting the IB, @techanvil !


> * Determine the `label` for the GA event: `none-selected` when `didSetAudiences` is true, otherwise `no-longer-available`.

To confirm, shouldn't this be the other way around, i.e. `none-selected` when `didSetAudiences` is false, otherwise `no-longer-available`?

Please confirm, thank you!

**Comment by techanvil** [comment]
Thanks for catching that @nfmohit! You are spot on, it should be the other way round. I've fixed the IB, back over to you! 🦅 👁

**Comment by nfmohit** [comment]
Thank you Tom! IB ✅

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Verified the GTM events as per the table in ACs and all are being triggered accordingly.
Moving ticket to approval.

-  `no-longer-available` label
   <Details>
   view_banner: 

   ![Image](https://github.com/user-attachments/assets/af9f742e-24ba-4fa1-afc0-862ce88174b1)
    
   select_groups:

   ![Image](https://github.com/user-attachments/assets/bf6d860d-dc54-46c6-846d-e66cdf980271)
   
   change_settings:

    ![Image](https://github.com/user-attachments/assets/344ed6cc-9ea7-4486-9312-97ff664f2f8d)

   </Details>

- `none-selected` label

   <Details>
   view_banner: 
   
   ![Image](https://github.com/user-attachments/assets/d3761e76-0338-4a79-a1ea-40330451a613)

   
   select_groups:

   ![Image](https://github.com/user-attachments/assets/40d25031-1b05-48e6-a035-7ce0cbb06911)

   change_settings:

   ![Image](https://github.com/user-attachments/assets/cf7570d8-3b36-4042-8eff-85cf340fba0a)

   </Details>


- `new-visitors` label
   <Details>
   view_notice:

   ![Image](https://github.com/user-attachments/assets/216ec25e-9546-484a-8d1b-bd51bad51344)

   dimiss_notice:

   ![Image](https://github.com/user-attachments/assets/b28ffaf2-d58c-4586-aa8c-f01d3c4ede95)

   </Details>

- `compare-metrics` label
   <Details>
   view_notice:

   ![Image](https://github.com/user-attachments/assets/07d57a63-bc94-4111-bbbd-b34d3fbe3e88)

   dimiss_notice:

   ![Image](https://github.com/user-attachments/assets/cde1b696-dad2-4063-a6a0-a22ee7302d92)

   </Details>

- `custom-audiences` label
   <Details>

   view_notice:

   ![Image](https://github.com/user-attachments/assets/7b83c796-10d4-4033-8f9a-48de261dbe89)

   dimiss_notice:

   ![Image](https://github.com/user-attachments/assets/ea60fdd4-e69f-46a0-884d-c07bbc509a26)

   </Details>

- `purchasers` label
   <Details>
   view_notice:

   ![Image](https://github.com/user-attachments/assets/c64f2056-5b2a-47cd-9a92-cfd62763838e)

   dimiss_notice:

   ![Image](https://github.com/user-attachments/assets/7a5b32b7-e14e-4251-9cbb-a34ffd7936d5)

   </Details>

- `returning-visitors` label
   <Details>
   view_notice:

   ![Image](https://github.com/user-attachments/assets/20b66193-9672-451b-aa0c-204451280c36)

   dimiss_notice:
   
   ![Image](https://github.com/user-attachments/assets/d16f5eb7-59ff-4d9a-a7f0-ee2d5c586534)

   </Details>

- `compare-new-returning`  label
   <Details>
   view_notice:

   ![Image](https://github.com/user-attachments/assets/9bde7d8d-7dfb-4145-bbfa-352301f53852)

   dimiss_notice:

   ![Image](https://github.com/user-attachments/assets/433e04e8-8a7a-4cec-a16a-aba0c01cfe2c)

   </Details>

- `compare-cities label`
   <Details>
   view_notice:

   ![Image](https://github.com/user-attachments/assets/a9261647-477d-4a25-a2e4-cf1f314815eb)

   dimiss_notice:

   ![Image](https://github.com/user-attachments/assets/99d619be-306c-484a-9712-155314042c3d)

   </Details>
