### ISSUE TITLE
Add GA event tracking for the Audience Selection Panel

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#9497]
## Feature Description

GA events should be added to keep track of interaction with the Audience Selection Panel.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

The following GA events should be tracked for the given actions. See the [GA events sheet](https://docs.google.com/spreadsheets/d/1eEuJ2ppVZuai1_hL77RA2vL7DUidM_qCnvTsjxZ_S4k/edit?gid=925918307#gid=925918307&range=432:449).

Event Name | Category | Label | Trigger | Condition | Description/details
-- | -- | -- | -- | -- | --
change_groups | {viewContext}_audiences-sidebar |  | Click | User clicks the ["Change groups" CTA](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1046-42473&node-type=frame&t=PNTGwXm0OYTItlYB-0) to open the Selection Panel
audiences_sidebar_view | {viewContext}_audiences-sidebar |  | Element visibility  | User views the [Audiences Selection Panel](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1106-16323&node-type=frame&t=PNTGwXm0OYTItlYB-0)  | "Sidebar" events named for consistency with the corresponding event for KMW
audiences_sidebar_save | {viewContext}_audiences-sidebar | count of audiences by category in the format "user:123,site-kit:456,default:789" | Click | User clicks "Save selection" in the Selection Panel
audiences_sidebar_cancel | {viewContext}_audiences-sidebar |  | Click | User clicks "Cancel" in the Selection Panel
insufficient_permissions_error | {viewContext}_audiences-sidebar |  | Element visibility  | User views the [insufficient permissions error](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1721-23197&node-type=frame&t=PNTGwXm0OYTItlYB-0) when loading the Selection Panel data
insufficient_permissions_error_request_access | {viewContext}_audiences-sidebar |  | Click | User clicks "Request access" on the error
data_loading_error | {viewContext}_audiences-sidebar |  | Element visibility  | User views the [generic error](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1705-15994&node-type=frame&t=PNTGwXm0OYTItlYB-0) when loading the Selection Panel data
data_loading_error_retry | {viewContext}_audiences-sidebar |  | Click | User clicks "Retry" on the error
view_notice | {viewContext}_audiences-sidebar-create-audiences |  | Element visibility  | User views the [Audience Creation Notice](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1821-25183&node-type=frame&t=PNTGwXm0OYTItlYB-0) in the Selection Panel
create_audience | {viewContext}_audiences-sidebar-create-audiences | one of "new-visitors", "returning-visitors" | Click | User clicks "Create" for one of the audiences in the notice
view_oauth_notice | {viewContext}_audiences-sidebar-create-audiences |  | Element visibility  | User views the [OAuth notice](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1821-26283&node-type=frame&t=PNTGwXm0OYTItlYB-0) in the Audiences Creation Notice |
dismiss_oauth_notice | {viewContext}_audiences-sidebar-create-audiences |  |  | User clicks "Got it" on the OAuth notice
view_notification | {viewContext}_audiences-sidebar-create-audiences-success |  |  | User views the [success notification](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1821-26283&node-type=frame&t=PNTGwXm0OYTItlYB-0) in the Audience Creation Notice
dismiss_notification | {viewContext}_audiences-sidebar-create-audiences-success |  |  | User clicks "Got it" on the notification
auth_error | {viewContext}_audiences-sidebar-create-audiences |  | Element visibility  | User views the [OAuth error notice](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1821-26925&node-type=frame&t=PNTGwXm0OYTItlYB-0) in the Audience Creation Notice when an error occurs during audience creation
insufficient_permissions_error | {viewContext}_audiences-sidebar-create-audiences |  | Element visibility  | User views the [insufficient permissions error notice](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1340-29800&node-type=frame&t=PNTGwXm0OYTItlYB-0) in the Audience Creation Notice when an error occurs during audience creation
insufficient_permissions_error_request_access | {viewContext}_audiences-sidebar-create-audiences |  | Click | User clicks "Request access" on the error notice
setup_error | {viewContext}_audiences-sidebar-create-audiences |  | Element visibility  | User views the [generic error notice](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1393-11298&node-type=frame&t=PNTGwXm0OYTItlYB-0) in the Audience Creation Notice when an error occurs during audience creation

## Implementation Brief

- [x] In the [`ChangeGroupsLink`](https://github.com/google/site-kit-wp/blob/5a7a405fd007450fd0276df307a68f13c6e4d798/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/ChangeGroupsLink.js) component:
  - Call `trackEvent( '${viewContext}_audiences-sidebar', 'change_groups' )` in the `openAudiencesSelectionPanel()` callback.
- [x] In the [`AudienceSelectionPanel`](https://github.com/google/site-kit-wp/blob/5a7a405fd007450fd0276df307a68f13c6e4d798/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/index.js) component:
  - Call `trackEvent( '${viewContext}_audiences-sidebar', 'audiences_sidebar_view' )` in the `onSideSheetOpen()` callback.
- [x] In the [`AudienceSelectionPanel/Footer`](https://github.com/google/site-kit-wp/blob/5a7a405fd007450fd0276df307a68f13c6e4d798/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/Footer.js) component:
  - Retrieve `availableAudiences` via the `getAvailableAudiences()` selector.
  - Add an `onSaveSuccess` callback prop to the rendered `SelectionPanelFooter`:
    - Determine the `label` for the GA event in the format `user:123,site-kit:456,default:789` by mapping `configuredAudiences` to the number of audiences of the given type in the saved selection. The type can be determined by looking up the `audienceType` for an audience via `availableAudiences`; `123/456/789` are of course the number of audiences of the given type.
    - Call `trackEvent( '${viewContext}_audiences-sidebar', 'audiences_sidebar_save', label )`.
  - Add an `onCancel` callback prop to the rendered `SelectionPanelFooter`. In the callback, call `trackEvent( '${viewContext}_audiences-sidebar', 'audiences_sidebar_cancel' )`.
- [x] In the [`AudienceSelectionPanel/ErrorNotice`](https://github.com/google/site-kit-wp/blob/5a7a405fd007450fd0276df307a68f13c6e4d798/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/ErrorNotice.js) component:
  - Retrieve the selection panel's open state via the `CORE_UI` `AUDIENCE_SELECTION_PANEL_OPENED_KEY` value.
  - Create a variable, `hasErrors` which contains the value of `errors.length > 0`. This is to use in the `useEffect()` hook below to avoid passing `errors` as a dependency as `errors` will change more often.
  - Add a `useEffect()` hook.
    - Return early if the panel is closed or `hasErrors` is false.
    - If `hasInsufficientPermissionsError` is true, call `trackEvent( '${viewContext}_audiences-sidebar', 'insufficient_permissions_error' )`.
    - Otherwise, call `trackEvent( '${viewContext}_audiences-sidebar', 'data_loading_error' )`.
- [x] In the [`AudienceSelectionPanel/RequestAccessButton`](https://github.com/google/site-kit-wp/blob/5a7a405fd007450fd0276df307a68f13c6e4d798/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/RequestAccessButton.js) component:
  - Add an `onClick` callback prop to the rendered `Button`. In the callback, call `trackEvent( '${viewContext}_audiences-sidebar', 'insufficient_permissions_error_request_access' )`.
- [x] In the [`AudienceSelectionPanel/RetryButton`](https://github.com/google/site-kit-wp/blob/5a7a405fd007450fd0276df307a68f13c6e4d798/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/RetryButton.js) component:
  - Add an `onClick` callback prop to the rendered `Button`. In the callback, call `trackEvent( '${viewContext}_audiences-sidebar', 'data_loading_error_retry' )`.
- [x] In the [`AudienceCreationNotice`](https://github.com/google/site-kit-wp/blob/5a7a405fd007450fd0276df307a68f13c6e4d798/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/AudienceCreationNotice.js) component:
  - Retrieve the selection panel's open state via the `CORE_UI` `AUDIENCE_SELECTION_PANEL_OPENED_KEY` value.
  - Add a `useEffect()` hook.
    - If the panel is open and `shouldShowNotice` is true, call `trackEvent( '${viewContext}_audiences-sidebar-create-audiences', 'view_notice' )`.
  - Amend the `onClick` handler for the `SpinnerButton` component:
    - Determine the `label` for the event, which should be `new-visitors` or `returning-visitors` depending on which audience is being created.
    - Call `trackEvent( '${viewContext}_audiences-sidebar-create-audiences', 'create_audience', label )` prior to the call to `handleCreateAudience`. Chain the two calls using `.finally()`.
  - Add another `useEffect()` hook.
    - Return early if the panel is closed.
    - If the conditions for showing the `SubtleNotification` are true (i.e. if `! hasAnalytics4EditScope && ! isEditScopeNoticeDismissed`) call `trackEvent( '${viewContext}_audiences-sidebar-create-audiences', 'view_oauth_notice' )`.
  - Amend the `handleDismissEditScopeNotice()` callback:
    - Call `trackEvent( '${viewContext}_audiences-sidebar-create-audiences', 'dismiss_oauth_notice' )` prior to the call to `dismissItem`. Chain the two calls using `.finally()`.
- [x] In the [`AudienceCreationSuccessNotice`](https://github.com/google/site-kit-wp/blob/5a7a405fd007450fd0276df307a68f13c6e4d798/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/AudienceCreationSuccessNotice.js) component:
  - Retrieve the selection panel's open state via the `CORE_UI` `AUDIENCE_SELECTION_PANEL_OPENED_KEY` value.
  - Add a `useEffect()` hook.
    - If the panel is open and `showSuccessNotice` is true, call `trackEvent( '${viewContext}_audiences-sidebar-create-audiences-success', 'view_notification' )`.
  - Amend the `onClick` handler for the `Button` component:
    - Call `trackEvent( '${viewContext}_audiences-sidebar-create-audiences-success', 'dismiss_notification' )` prior to the call to `setValue`. Chain the two calls using `.finally()`.
- [x] In the [`AudienceCreationErrorNotice`](https://github.com/google/site-kit-wp/blob/5a7a405fd007450fd0276df307a68f13c6e4d798/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/AudienceCreationErrorNotice.js) component:
  - Create a variable, `hasErrors` which contains the value of `errors.length > 0`. This is to use in the `useEffect()` hook below to avoid passing `errors` as a dependency as `errors` will change more often.
  - Add a `useEffect()` hook.
    - Return early if `hasErrors` is false.
    - If `hasOAuthError` is true, call `trackEvent( '${viewContext}_audiences-sidebar-create-audiences', 'auth_error' )`.
    - Otherwise, if `hasInsufficientPermissionsError` is true, call `trackEvent( '${viewContext}_audiences-sidebar-create-audiences', 'insufficient_permissions_error' )`.
    - Otherwise, call `trackEvent( '${viewContext}_audiences-sidebar-create-audiences', 'setup_error' )`.
  - Add an `onClick` callback prop to the rendered `Button`. In the callback, call `trackEvent( '${viewContext}_audiences-sidebar-create-audiences', 'insufficient_permissions_error_request_access' )`.

### Test Coverage

- Add JS test coverage for the above changes where tests exist for the affected components.

## QA Brief

* Turn on the `audienceSegmentation` feature flag.
* Set up Site Kit with the Analytics module.
* Enable the user groups/audience segmentation feature.
* Use a Google Analytics debugger tool, like the "Google Analytics Debugger" Chrome extension.
* Go through each of the conditions mentioned in the ACs and verify that the respective GA event is tracked.

## Changelog entry

* Add GA event tracking for user interactions with the Audience Selection Panel.

**Comment by nfmohit** [comment]
IB ✅

**Comment by nfmohit** [comment]
Thank you for sharing your observations, @kelvinballoo !

> **ITEM 1:** For the audiences_sidebar_save event, we are expecting the label to be a count of audiences by category in the format "user:123,site-kit:456,default:789"
> 
> My question is what do the numbers represent? What is the expectation for these? Currently during my testing, I had "user:0,site-kit:2,default:0" I am unable to verify the accuracy of those numbers.

The numbers represent the number of audiences under each category. In your case, you seem to have saved the audience selection with 0 user audiences, 2 Site Kit audiences, and 0 default audiences. Does that help?

> **ITEM 2:**
> For the dismiss_oauth_notice event, it would be when User clicks "Got it" on the OAuth notice.
> Per my testing, I could not see the 'Got it' button from the oauth_notice.
> Could you double check the attached image and let me know if that's the correct notice to check or we indeed do not have a 'Got it' button?

The `oauth_notice` actually refers to this notice:
![Image](https://github.com/user-attachments/assets/f602f388-fe84-470b-8af5-464d3e5caeef)

The notice you're referring to in your screenshot will have the following tracking criteria:

<table>
<tr>
 <td>auth_error
 <td>{viewContext}_audiences-sidebar-create-audiences
 <td>Element visibility
 <td>User views the [OAuth error notice](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1821-26925&node-type=frame&t=PNTGwXm0OYTItlYB-0) in the Audience Creation Notice when an error occurs during audience creation</td>
</table>

> **ITEM 3:** For the view_notification event, it triggers when user views the success notification in the Audience Creation Notice.
> 
> Let's say there are 2 audiences to be created: New and Returning
> 
> * If I create for the 'New' audience, the event is fired accordingly.
> * Now, if I go on to create for 'Returning' audience, the success message remains but there is a no new firing of the event. Should we be firing it one more time?

With the way it is currently built, the notice doesn't reappear once it is already visible, hence, the event is also tracked once. It might be worth checking with @techanvil to see if the notice should reappear, and if so, a new issue is warranted here.

Please let me know if you have any other questions, thanks!

**Comment by techanvil** [comment]
> > **ITEM 3:** For the view_notification event, it triggers when user views the success notification in the Audience Creation Notice.
> > Let's say there are 2 audiences to be created: New and Returning
> > 
> > * If I create for the 'New' audience, the event is fired accordingly.
> > * Now, if I go on to create for 'Returning' audience, the success message remains but there is a no new firing of the event. Should we be firing it one more time?
> 
> With the way it is currently built, the notice doesn't reappear once it is already visible, hence, the event is also tracked once. It might be worth checking with [@techanvil](https://github.com/techanvil) to see if the notice should reappear, and if so, a new issue is warranted here.
> 
> Please let me know if you have any other questions, thanks!

Thanks @kelvinballoo and @nfmohit. As Nahid has pointed out the notice is already visible, there's no need to hide/reshow it in response to the second audience creation and we don't need to track an additional event in the above scenario.

**Comment by kelvinballoo** [comment]
### QA Update ⚠ 

Hi @nfmohit ,

**ITEM 1:**
It does help but there seems to be a discrepancy between the audiences that I saved and what is being tracked.
If you see in my previous screenshot, the audience selected was only 'New Visitors' but it registered 2. It should have been 1.
I have documented other discrepancies in the attached video for you to review.

<Details>

https://github.com/user-attachments/assets/ee9515ee-e9ca-476f-986c-4accc95729d4

</Details>

_____________________________________________________________________________________

**ITEM 2:**
I was trying to look into steps to re-create that oAuth notice but could not successfully find the steps from other tickets.
Could you elaborate on the steps to get the `oauth_notice` that you pointed out please.

_____________________________________________________________________________________

**ITEM 3:**
Noted on that.

**Comment by nfmohit** [comment]
Thank you for the follow-up, @kelvinballoo!

> **ITEM 1:**
> It does help but there seems to be a discrepancy between the audiences that I saved and what is being tracked.
> If you see in my previous screenshot, the audience selected was only 'New Visitors' but it registered 2. It should have been 1.
> I have documented other discrepancies in the attached video for you to review.

I investigated, was able to replicate the issue, and opened [a follow-up PR](https://github.com/google/site-kit-wp/pull/9640).

> **ITEM 2:**
> I was trying to look into steps to re-create that oAuth notice but could not successfully find the steps from other tickets.
> Could you elaborate on the steps to get the `oauth_notice` that you pointed out please.

You should be able to see this by deleting the `wp_googlesitekit_additional_auth_scopes` option from the `PREFIX_usermeta` table for your user.

**Comment by techanvil** [comment]
Back to you for another pass, @kelvinballoo!

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Tested ITEM 1 and the audiences saved are now reflecting accordingly on the label.
<Details>

![Image](https://github.com/user-attachments/assets/8b8c192b-1fcf-43f2-9d23-6b22972a9503)

![Image](https://github.com/user-attachments/assets/7b13b6c6-bce0-42fe-964c-b7a2194ac74c)

![Image](https://github.com/user-attachments/assets/da01136e-14fb-4ab5-89cd-ec586b1298bc)

![Image](https://github.com/user-attachments/assets/8b9f5327-7cb6-4946-9f3a-065fdc2c53c1)

![Image](https://github.com/user-attachments/assets/a0f3bb66-025a-4706-98db-4ed175fcf9e7)

</Details>

Other than that, all the events are being tracked accordingly too as detailed further down.
The screenshots include ITEM 2 as well.

Moving ticket to approval.

- change_groups
   <Details>

   ![Image](https://github.com/user-attachments/assets/6eea2a75-dad8-4a43-895f-364b6039564d)

   </Details>
- audiences_sidebar_view
   <Details>

   ![Image](https://github.com/user-attachments/assets/f6b87a93-90c3-4dec-875d-1a23dfb93a58)

   </Details> 
- audiences_sidebar_save
   <Details>

   ![Image](https://github.com/user-attachments/assets/0c6209b5-4d86-401a-88dd-6d1e02118de8)

   </Details> 
- audiences_sidebar_cancel
   <Details>

   ![Image](https://github.com/user-attachments/assets/97779c91-3c16-4b99-856c-7412859ec9a5)

   </Details> 
- insufficient_permissions_error (audiences-sidebar)
   <Details>

   ![Image](https://github.com/user-attachments/assets/e4966535-c38f-4b49-b8b8-029b4455176b)

   </Details>
- insufficient_permissions_error_request_access (audiences-sidebar)
   <Details>

   ![Image](https://github.com/user-attachments/assets/a89cc93d-a4bb-416f-b99d-5b271ea8351a)

   </Details>
- data_loading_error
   <Details>

   ![Image](https://github.com/user-attachments/assets/567f6805-d4b4-47a4-b587-bb446a18824f)

   </Details>
- data_loading_error_retry
   <Details>

   ![Image](https://github.com/user-attachments/assets/10c1e11e-1f2d-476e-98ed-cc97cf49fcc5)

   </Details>
- view_notice
   <Details>

   ![Image](https://github.com/user-attachments/assets/b590755b-7755-483d-8157-2724b50d3d90)

   ![Image](https://github.com/user-attachments/assets/bf9c8e1e-27f8-4713-b9ab-fd675912eff6)

   ![Image](https://github.com/user-attachments/assets/f0b7eaf2-8558-46bf-b0db-977ea9dc8c50)


   </Details>
- create_audience
   <Details>

   ![Image](https://github.com/user-attachments/assets/a62e0243-81b1-4493-88b0-b90745ae7c9e)

   ![Image](https://github.com/user-attachments/assets/40b876c7-594e-445c-b2e4-084ed7ae126a)

   </Details>
- view_oauth_notice
   <Details>

   ![Image](https://github.com/user-attachments/assets/47f969ec-4e24-4da5-bd1b-422b4be87e38)

   </Details>
- dismiss_oauth_notice
   <Details>

   ![Image](https://github.com/user-attachments/assets/aa73bd7f-3d75-4ee3-a9e5-4734e01becd1)

   </Details>
- view_notification
   <Details>

   ![Image](https://github.com/user-attachments/assets/c2d9c038-f1aa-4482-862f-28d4af1f90ab)

   </Details>
- dismiss_notification
   <Details>

   ![Image](https://github.com/user-attachments/assets/ef18fced-69c3-4017-83c3-0692ace3ffaa)

   </Details>
- auth_error
   <Details>

   ![Image](https://github.com/user-attachments/assets/cf4e5e39-c149-4e0d-990b-ac11bfb915c8)

   </Details>
- insufficient_permissions_error (audiences-sidebar-create-audiences)
   <Details>

   ![Image](https://github.com/user-attachments/assets/c4ed67c1-dba9-4462-8a62-d43216e2ea06)

   </Details>
- insufficient_permissions_error_request_access (audiences-sidebar-create-audiences)
   <Details>

   ![Image](https://github.com/user-attachments/assets/5f1f5522-0bc2-46cf-b118-6dc7d3ffbc6f)

   </Details>
- setup_error (audiences-sidebar-create-audiences)
   <Details>

   ![Image](https://github.com/user-attachments/assets/6fcc3126-440d-4f67-add7-19f2f697d43c)

   </Details>
