### ISSUE TITLE
Add GA event tracking for the Settings section

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#9499]
## Feature Description

GA events should be added to keep track of interaction with the Settings section, exclusing those events which are shared with the dashboard Setup CTA Banner (see #9493).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

The following GA events should be tracked for the given actions. See the [GA events sheet](https://docs.google.com/spreadsheets/d/1eEuJ2ppVZuai1_hL77RA2vL7DUidM_qCnvTsjxZ_S4k/edit?gid=925918307#gid=925918307&range=450:452).

Event Name | Category | Trigger | Condition | Description/details
-- | -- | -- | -- | --
enable_groups | {viewContext}_audiences-setup-cta-settings | Click | User clicks "Enable groups" | Setup and error events relating to the CTA are defined in #9493, see the "{viewContext}_audiences-setup" event category
view_notification | {viewContext}_audiences-setup-cta-settings-success | Element visibility  | User views the [Audience Segmentation Setup Success notification](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1415-15958&node-type=frame&t=PJX3Y7OESgwokk2d-0) on the Settings screen
confirm_notification | {viewContext}_audiences-setup-cta-settings-success | Click | User clicks "Show me" on the notification
dismiss_notification | {viewContext}_audiences-setup-cta-settings-success | Click | User clicks "Got it" on the notification
audience_widgets_enable | {viewContext}_audiences-settings | Click | User clicks the toggle to enable the audiences widget area
audience_widgets_disable | {viewContext}_audiences-settings | Click | User clicks the toggle to disable the audiences widget area

## Implementation Brief

- [x] In the [`SettingsCardVisitorGroups/SetupCTA`](https://github.com/google/site-kit-wp/blob/2be4a2903ca645ad03f331ff0c3072871d81d6fe/assets/js/modules/analytics-4/components/audience-segmentation/settings/SettingsCardVisitorGroups/SetupCTA.js) component:
  - Create a `handleEnableGroups()` callback:
    - Call `trackEvent( '${viewContext}_audiences-setup-cta-settings', 'enable_groups' )`, followed by `onEnableGroups()`. Chain the two calls using `trackEvent().finally()`.
  - Replace `onEnableGroups` with `handleEnableGroups` as the value for the `onClick` prop that is passed to `Link`.
- [x] Refactor the [`SettingsCardVisitorGroups/SetupSuccess`](https://github.com/google/site-kit-wp/blob/2be4a2903ca645ad03f331ff0c3072871d81d6fe/assets/js/modules/analytics-4/components/audience-segmentation/settings/SettingsCardVisitorGroups/SetupSuccess.js) component to be a module with its own folder and an `index.js` file.
- [x] Extract the [rendered JSX content](https://github.com/google/site-kit-wp/blob/070023a03af45a723ff6121646b1f391ad48a787/assets/js/modules/analytics-4/components/audience-segmentation/settings/SettingsCardVisitorGroups/SetupSuccess.js#L74-L94) from the `SetupSuccess` component to a new component e.g. `SetupSuccessContent`.
  - Wrap the `SetupSuccessContent` component in `forwardRef()` so a `ref` can be passed to it, and add the `ref` to its top-level rendered element.
- [x] In the `SettingsCardVisitorGroups/SetupSuccess` component:
  - Create a version of `SetupSuccessContent` wrapped by the `withIntersectionObserver()` HOC, e.g. `SetupSuccessContentWithIntersectionObserver`. Render this in place of the existing `SetupSuccessContent` instance.
  - Pass the `onInView` callback prop to `SetupSuccessContentWithIntersectionObserver`. In the callback, call `trackEvent( '${viewContext}_audiences-setup-cta-settings-success', 'view_notification' )`.
- [x] In the `SetupSuccessContent` component:
  - Amend the `scrollToWidgetArea()` callback:
    - Replace the call to `dismissNotificationForUser()` with a direct call to `dismissItem()` (alternatively, refactor the call to `dismissItem()` to a reusable function).
    - Call `trackEvent( '${viewContext}_audiences-setup-cta-settings-success', 'confirm_notification' )` prior to the calls to `dismissItem()` and `navigateTo()`. Chain the calls using `trackEvent().finally()`.
  - Amend the `dismissNotificationForUser()` callback:
    - Call `trackEvent( '${viewContext}_audiences-setup-cta-settings-success', 'dismiss_notification' )` prior to the call to `dismissItem()`. Chain the two calls using `trackEvent().finally()`.
- [x] In the [`SettingsCardVisitorGroups`](https://github.com/google/site-kit-wp/blob/2be4a2903ca645ad03f331ff0c3072871d81d6fe/assets/js/modules/analytics-4/components/audience-segmentation/settings/SettingsCardVisitorGroups/index.js) component:
  - Amend the `handleKeyMetricsToggle()` callback:
    - Determine the `action` for the GA event: `audience_widgets_enable` when `audienceSegmentationWidgetHidden` is true, otherwise `audience_widgets_disable`.
    - Call `trackEvent( '${viewContext}_audiences-settings', action )` prior to the calls to `setAudienceSegmentationWidgetHidden()` and `saveAudienceSettings()`. Chain the calls using `trackEvent().finally()`.

### Test Coverage

* Add JS test coverage for the above changes where tests exist for the affected components.

## QA Brief

- Have a mechanism for checking tracked Analytics events ready, e.g. Tag Assistant or the Google Analytics Debugger Chrome extension.
- Set up Site Kit with the `audienceSegmentation` feature flag enabled, tracking enabled, and Analytics connected using a property which is out of the gathering data state.
- Navigate to the **Settings > Admin Settings** screen, click on **Enable groups** and verify that the `enable_groups` event is tracked as per the AC.
- Proceed through the OAuth flow to set up the feature. Upon returning to Site Kit, the success notification should be displayed.
- Verify the `view_notification` event is tracked as per the AC.
- Click on **Show me** on the notification and verify the `confirm_notification` event is tracked as per the AC.
- Run through the steps above to set the feature up again. This time, Click on **Got it** on the notification and verify the `dismiss_notification` event is tracked as per the AC.
- Toggle the **Display visitor groups in dashboard** switch and verify the `audience_widgets_enable` and `audience_widgets_disable` events are tracked as per the AC.

## Changelog entry

* Add GA event tracking for user interactions with the Audience Segmentation Setup in the Settings section.

**Comment by nfmohit** [comment]
Thank you for drafting the IB, @techanvil.

> In the `SettingsCardVisitorGroups/SetupCTA` component:
> 
> * Create a version of `SetupSuccessContent` wrapped by the `withIntersectionObserver()` HOC, e.g. `SetupSuccessContentWithIntersectionObserver`. Render this in place of the existing `SetupSuccessContent` instance.
> *

Just to confirm, did you mean `SettingsCardVisitorGroups/SetupSuccess` (`assets/js/modules/analytics-4/components/audience-segmentation/settings/SettingsCardVisitorGroups/SetupSuccess/index.js`) instead?

**Comment by techanvil** [comment]
I certainly did, thanks for spotting another copy/pasta @nfmohit! I've updated the IB, cheers.

**Comment by nfmohit** [comment]
Brilliant, thanks Tom! IB ✅

**Comment by kelvinballoo** [comment]
### QA Update ✅ 

Verified good. All events are being tracked as per the AC.
Moving ticket to approval.

- enable_groups
   <Details>

   ![Image](https://github.com/user-attachments/assets/6aaa92f9-1d3d-4559-89b6-750caf98eaba)

   </Details>

- view_notification
   <Details>

   ![Image](https://github.com/user-attachments/assets/4ba64261-f4b1-413d-a2c3-5c957f1a9b3e) 

   </Details>

- confirm_notification
   <Details>

   ![Image](https://github.com/user-attachments/assets/1e5b0467-91d1-4147-9ebf-f5883b6b6de5)

   </Details>

- dismiss_notification
   <Details>

   ![Image](https://github.com/user-attachments/assets/83f623fa-e6e6-4b7d-88fc-b34d54a2b3fc)

   </Details>

- audience_widgets_enable
   <Details>

   ![Image](https://github.com/user-attachments/assets/9810d0ab-f551-4754-8e32-f0964262f619)

   </Details>

- audience_widgets_disable
   <Details>

   ![Image](https://github.com/user-attachments/assets/d1f0f549-17b4-4e09-b412-939fcb8fe0d5)

   </Details>
