### ISSUE TITLE
Implement GA4 Tracking Events for First-Party Mode Interactions

### ISSUE THREAD

**Issue by hussain-t** [google/site-kit-wp#9669]
## Feature Description

Introduce GA4 tracking events to monitor user interactions with the First-party mode banner notification, success setup notification, and toggle. These events will provide insights into user engagement and adoption of First-party mode, helping to understand behavior around this feature.

For details, refer to the [Design Doc](https://docs.google.com/document/d/1PHptJ1Js_1OZrk5kRwoB3zPB2KQrXLJV7-3izi-bB30/edit?tab=t.0#heading=h.jg6d9cu8m3w1).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The following GA4 tracking events should be implemented to monitor user interactions with the First-party mode feature. Each event is described below in a table format:

#### Setup CTA Banner

| **Event Name / Action** | **Category**                                | **Label** | **Trigger**          | **Description**                                                           |
|--------------------------|---------------------------------------------|-----------|----------------------|---------------------------------------------------------------------------|
| view_notification        | `{viewContext}_fpm-setup-cta` |           | element visibility   | User views the setup CTA for First-party mode.                            |
| confirm_notification     | `{viewContext}_fpm-setup-cta` |           | click                | User clicks “Enable First-party mode” CTA.                                |
| click_learn_more_link    | `{viewContext}_fpm-setup-cta` |           | click                | User clicks the “Learn more” link in the notification.                    |
| dismiss_notification     | `{viewContext}_fpm-setup-cta` |           | click                | User clicks “Maybe later.”                                                |
| tooltip_view             | `{viewContext}_fpm-setup-cta` |           | element visibility   | User hovers or focuses on the tooltip to view details.                    |
| tooltip_dismiss          | `{viewContext}_fpm-setup-cta` |           | click                | User dismisses the tooltip.                                               |

---

#### Setup Success Notification

| **Event Name / Action** | **Category**                                   | **Label** | **Trigger**        | **Description**                                                           |
|--------------------------|-----------------------------------------------|-----------|--------------------|---------------------------------------------------------------------------|
| view_notification        | `{viewContext}_setup-success-notification-fpm` |           | element visibility | User views the setup success notification for First-party mode.           |
| dismiss_notification     | `{viewContext}_setup-success-notification-fpm` |           | click              | User dismisses the success notification for First-party mode.             |

---

#### Toggle Switch

| **Event Name / Action**    | **Category**                                | **Label** | **Trigger**        | **Description**                                                           |
|-----------------------------|---------------------------------------------|-----------|--------------------|---------------------------------------------------------------------------|
| activate_first_party_mode   | `{viewContext}_fpm-settings-toggle`         |           | click              | User activates the toggle to enable First-party mode.                     |
| deactivate_first_party_mode | `{viewContext}_fpm-settings-toggle`         |           | click              | User deactivates the toggle to disable First-party mode.                  |
| click_learn_more_link         | `{viewContext}_fpm-settings-toggle`         |           | click              | User clicks "Learn more" link in the toggle description.                  |
| view_notice                 | `{viewContext}_fpm-settings-toggle-disabled`|           | element visibility | Warning message displays when First-party mode is disabled.               |
| click_learn_more_link       | `{viewContext}_fpm-settings-toggle-disabled`|           | click              | User clicks “Learn more” link in the warning notice.                      |

---

#### Warning Notification Dashboard

| **Event Name / Action** | **Category**                           | **Label** | **Trigger**          | **Description**                                                           |
|--------------------------|---------------------------------------|-----------|----------------------|---------------------------------------------------------------------------|
| view_notification        | `{viewContext}_warning-notification-fpm` |           | element visibility   | User views the warning notification related to First-party mode on the dashboard. |
| click_learn_more_link    | `{viewContext}_warning-notification-fpm` |           | click                | User clicks the “Learn more” link in the warning notification on the dashboard.   |
| dismiss_notification     | `{viewContext}_warning-notification-fpm` |           | click                | User dismisses the warning notification on the dashboard.                |

#### Setup CTA Banner

- [x] In the [`FirstPartyModeSetupBanner`](https://github.com/google/site-kit-wp/blob/b5816b5701f02da1b6ab099e83467719e7b7e63f/assets/js/components/notifications/FirstPartyModeSetupBanner.js) component:
  - Add a `useEffect()` hook:
    - If `isTooltipVisible` is true, call `trackEvent( '${viewContext}_fpm-setup-cta', 'tooltip_view' )`.
  - Pass the `onDismiss` callback prop to `AdminMenuTooltip`. In the callback, call `trackEvent( '${viewContext}_fpm-setup-cta', 'tooltip_dismiss' )`.
- [x] Update the notification slug for the component to be `fpm-setup-cta` instead of `first-party-mode-setup-cta-banner` as it is currently defined:
      https://github.com/google/site-kit-wp/blob/b5816b5701f02da1b6ab099e83467719e7b7e63f/assets/js/googlesitekit/notifications/register-defaults.js#L448
- [x] Update the corresponding CSS class names in `_googlesitekit-first-party-mode-setup-cta-banner.scss`:
      https://github.com/google/site-kit-wp/blob/b5816b5701f02da1b6ab099e83467719e7b7e63f/assets/sass/components/first-party-mode/_googlesitekit-first-party-mode-setup-cta-banner.scss#L21-L31
- [x] Ensure the remaining events are being tracked via the notifications framework. No additional implementation should be necessary.

#### Setup Success Notification

- [x] Review the [`FirstPartyModeSetupSuccessSubtleNotification`](https://github.com/google/site-kit-wp/blob/b5816b5701f02da1b6ab099e83467719e7b7e63f/assets/js/components/notifications/FirstPartyModeSetupSuccessSubtleNotification.js) component.
  - Ensure the events are being tracked via the notifications framework. No additional implementation should be necessary.

#### Toggle Switch

- [x] In the [`FirstPartyModeToggle`](https://github.com/google/site-kit-wp/blob/b5816b5701f02da1b6ab099e83467719e7b7e63f/assets/js/components/first-party-mode/FirstPartyModeToggle.js) component:
  - Amend the `handleClick()` callback:
    - Determine the `action` for the GA event: `deactivate_first_party_mode` when `isFirstPartyModeEnabled` is true, otherwise `activate_first_party_mode`.
    - Call `trackEvent( '${viewContext}_fpm-settings-toggle', action )` prior to the call to `setFirstPartyModeEnabled()`. Chain the calls using `trackEvent().finally()`.
  - Create a version of `SubtleNotification` wrapped by the `withIntersectionObserver()` HOC, e.g. `SubtleNotificationWithIntersectionObserver`. Render this in place of the existing `SubtleNotification` instance.
    - Pass the `onInView` callback prop to `SubtleNotificationWithIntersectionObserver`. In the callback, call `trackEvent( '${viewContext}_fpm-settings-toggle-disabled', 'view_notice' )`.
  - Pass the `onClick` callback prop the "learn more" `Link` component (to be added via https://github.com/google/site-kit-wp/issues/9699). In the callback, call `trackEvent( '${viewContext}_fpm-settings-toggle-disabled', 'click_learn_more_link' )`.

#### Warning Notification Dashboard

- [x] Review the `FirstPartyModeWarningNotification` component (to be added via https://github.com/google/site-kit-wp/issues/9767).
  - Ensure the events are being tracked via the notifications framework. No additional implementation should be necessary.

### Test Coverage

- Add JS test coverage for the above changes where tests exist for the affected components.

## QA Brief

- As a prerequisite for testing the events for each scenario:
  - Have a mechanism for checking tracked Analytics events ready, e.g. Tag Assistant or the Google Analytics Debugger Chrome extension.
  - Set up Site Kit with the `firstPartyMode` feature flag enabled, tracking enabled, and Ads and/or Analytics connected.

#### Setup CTA Banner

- When the Setup CTA Banner appears, verify the `view_notification` event with category `{viewContext}_fpm-setup-cta` is tracked as per the AC.
- Click on **Learn more** in the banner and verify the `click_learn_more_link` event with category `{viewContext}_fpm-setup-cta` is tracked as per the AC.
- Click on **Enable First-party mode** to enable First-party mode.
- Verify the `confirm_notification` event with category `{viewContext}_fpm-setup-cta` is tracked as per the AC.
- Either set up Site Kit again on a fresh site, or reset SK, delete the `googlesitekitpersistent_dismissed_items` DB entry from the `usermeta` table to ensure the Setup CTA Banner will reappear and setup SK again.
- This time, click on **Maybe later** to dismiss the CTA.
- Verify the `dismiss_notification` event with category `{viewContext}_fpm-setup-cta` is tracked as per the AC.
- The Settings tooltip should appear. Verify the `tooltip_view` event is tracked as per the AC.
- Close the tooltip. Verify the `tooltip_dismiss` event is tracked as per the AC.

#### Setup Success Notification

- When the Setup CTA Banner appears, click on **Enable First-party mode** to enable First-party mode.
- The Setup Success Banner should appear.
- Verify the `view_notification` event with category `{viewContext}_setup-success-notification-fpm` is tracked as per the AC.
- Click on **Got it** to dismiss the banner.
- Verify the `dismiss_notification` event with category `{viewContext}_setup-success-notification-fpm` is tracked as per the AC.

#### Toggle Switch

- Navigate to the Analytics settings edit page.
- Toggle the **First-party mode** switch on and verify the `activate_first_party_mode` event with category `{viewContext}_fpm-settings-toggle` is tracked as per the AC.
- Toggle the **First-party mode** switch off and verify the `deactivate_first_party_mode` event with category `{viewContext}_fpm-settings-toggle` is tracked as per the AC.
- Click on **Learn more** in the toggle description.
- Verify the `click_learn_more_link` event with category `{viewContext}_fpm-settings-toggle` is tracked as per the AC.
- Using the Tester plugin (version `1.14.0` or above), set one or both of **Force FPFE Health Check** and **Force FPM Script Access Check** to `disabled`.
- Refresh the Analytics settings edit page.
- The FPM Warning Notice should appear.
- Verify the `view_notice` event with category `{viewContext}_fpm-settings-toggle-disabled` is tracked as per the AC.
- Click on **Learn more** in the warning notice.
- Verify the `click_learn_more_link` event with category `{viewContext}_fpm-settings-toggle-disabled` is tracked as per the AC.

#### Warning Notification Dashboard

- Enable First-party mode, either via the Setup CTA Banner or the toggle on the Analytics settings edit page.
- Using the Tester plugin, set one or both of **Force FPFE Health Check** and **Force FPM Script Access Check** to `disabled`.
- Navigate to the dashboard. The FPM Warning Notice should appear.
- Verify the `view_notification` event with category `{viewContext}_warning-notification-fpm` is tracked as per the AC.
- Click on **Learn more** in the notice.
- Verify the `click_learn_more_link` event with category `{viewContext}_warning-notification-fpm` is tracked as per the AC.
- Click on **Got it** to dismiss the notice.
- Verify the `dismiss_notification` event with category `{viewContext}_warning-notification-fpm` is tracked as per the AC.

## Changelog entry

* Introduce GA4 tracking events for the First-party mode feature.

**Comment by techanvil** [comment]
AC ✅

**Comment by techanvil** [comment]
Hey @hussain-t, sorry but having picked this up to write the IB I've realised that I was a bit quick to approve the AC.

The event categories for the notification events are defined in the AC as `{viewContext}_fpm_setup_cta_notification` and  `{viewContext}_fpm_setup_success_notification`. However, to align with the new notifications framework, these categories should [use the IDs](https://github.com/google/site-kit-wp/blob/b5816b5701f02da1b6ab099e83467719e7b7e63f/assets/js/googlesitekit/notifications/hooks/useNotificationEvents.js#L30-L72) for the notifications.

The IDs are currently defined as `first-party-mode-setup-cta-banner` and `setup-success-notification-fpm`, which would make the event categories `{viewContext}_first-party-mode-setup-cta-banner` and `{viewContext}_setup-success-notification-fpm`.

https://github.com/google/site-kit-wp/blob/b5816b5701f02da1b6ab099e83467719e7b7e63f/assets/js/googlesitekit/notifications/register-defaults.js#L448

https://github.com/google/site-kit-wp/blob/b5816b5701f02da1b6ab099e83467719e7b7e63f/assets/js/googlesitekit/notifications/register-defaults.js#L486

We can of course consider renaming the IDs but we do want to be consistent - for one thing all the notification IDs use kebab-case, and for another the subtle notification IDs follow the pattern `setup-success-notification-{module}` so I think we should keep `setup-success-notification-fpm` as it is.

We only have one other setup CTA banner registered at the moment - it has the ID `sign-in-with-google-setup-cta`. So we could consider renaming the FPM setup banner ID to `first-party-mode-setup-setup-cta` or `fpm-setup-cta`.

https://github.com/google/site-kit-wp/blob/b5816b5701f02da1b6ab099e83467719e7b7e63f/assets/js/modules/sign-in-with-google/index.js#L100

Either way we should update the categories for the notifications - and, for consistency I'd suggest updating the other categories too, to use kebab-case rather than snake_case.

**Comment by techanvil** [comment]
Here's a side-to-side view of the proposed changes:

#### Setup CTA Banner

```diff
< | view_notification        | {viewContext}_fpm_setup_cta_notification
< | confirm_notification     | {viewContext}_fpm_setup_cta_notification
< | click_learn_more_link    | {viewContext}_fpm_setup_cta_notification
< | dismiss_notification     | {viewContext}_fpm_setup_cta_notification
< | tooltip_view             | {viewContext}_fpm_setup_cta_notification
< | tooltip_dismiss          | {viewContext}_fpm_setup_cta_notification
---
> | view_notification        | {viewContext}_fpm-setup-cta
> | confirm_notification     | {viewContext}_fpm-setup-cta
> | click_learn_more_link    | {viewContext}_fpm-setup-cta
> | dismiss_notification     | {viewContext}_fpm-setup-cta
> | tooltip_view             | {viewContext}_fpm-setup-cta
> | tooltip_dismiss          | {viewContext}_fpm-setup-cta
```

#### Setup Success Notification

```diff
< | view_notification        | {viewContext}_fpm_setup_success_notification
< | dismiss_notification     | {viewContext}_fpm_setup_success_notification
---
> | view_notification        | {viewContext}_setup-success-notification-fpm
> | dismiss_notification     | {viewContext}_setup-success-notification-fpm
```

#### Toggle Switch

```diff
< | activate_first_party_mode   | {viewContext}_fpm_settings_toggle
< | deactivate_first_party_mode | {viewContext}_fpm_settings_toggle
< | view_notice                 | {viewContext}_fpm_settings_toggle_disabled
< | click_learn_more_link       | {viewContext}_fpm_settings_toggle_disabled
---
> | activate_first_party_mode   | {viewContext}_fpm-settings-toggle
> | deactivate_first_party_mode | {viewContext}_fpm-settings-toggle
> | view_notice                 | {viewContext}_fpm-settings-toggle-disabled
> | click_learn_more_link       | {viewContext}_fpm-settings-toggle-disabled
```

#### Warning Notification Dashboard

```diff
< | view_notification        | {viewContext}_fpm_warning_notification
< | click_learn_more_link    | {viewContext}_fpm_warning_notification
< | dismiss_notification     | {viewContext}_fpm_warning_notification
---
> | view_notification        | {viewContext}_fpm-warning-notification
> | click_learn_more_link    | {viewContext}_fpm-warning-notification
> | dismiss_notification     | {viewContext}_fpm-warning-notification
```

**Comment by techanvil** [comment]
As discussed on [Slack](https://fueled10up.slack.com/archives/C077DB69US2/p1733756099548619 I've updated the AC and the events [sheet](https://docs.google.com/spreadsheets/d/1eEuJ2ppVZuai1_hL77RA2vL7DUidM_qCnvTsjxZ_S4k/edit?gid=925918307#gid=925918307) with the above changes.

**Comment by nfmohit** [comment]
IB ✅

**Comment by techanvil** [comment]
Hey @hussain-t, just a heads up that I noticed we'd missed defining an event for when the "Learn more" link in the toggle description is clicked. I've added one to the AC & events sheet and will include it in the implementation.

![Image](https://github.com/user-attachments/assets/a489b0dd-d5de-4a26-a7d9-39d298366a49)

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

**Setup CTA Banner**

The Setup CTA Banner appears, the view_notification event with category {viewContext}_fpm-setup-cta is tracked The confirm_notification event with category {viewContext}_fpm-setup-cta is tracked as per the AC.
The dismiss_notification event with category {viewContext}_fpm-setup-cta is tracked as per the AC.
The view_notification event with category {viewContext}_setup-success-notification-fpm is tracked as per the AC.
The dismiss_notification event with category {viewContext}_setup-success-notification-fpm is tracked as per the AC.

**Toggle Switch**

The activate_first_party_mode event with category {viewContext}_fpm-settings-toggle is tracked as per the AC.
The deactivate_first_party_mode event with category {viewContext}_fpm-settings-toggle is tracked as per the AC.
The click_learn_more_link event with category {viewContext}_fpm-settings-toggle is tracked as per the AC.
The view_notice event with category {viewContext}_fpm-settings-toggle-disabled is tracked as per the AC.
The click_learn_more_link event with category {viewContext}_fpm-settings-toggle-disabled is tracked as per the AC.

**Warning Notification Dashboard**

The view_notification event with category {viewContext}_warning-notification-fpm is tracked as per the AC.
The click_learn_more_link event with category {viewContext}_warning-notification-fpm is tracked as per the AC.
The dismiss_notification event with category {viewContext}_warning-notification-fpm is tracked as per the AC.

<details>
 <summary>Screenshots</summary>
 
![Image](https://github.com/user-attachments/assets/e6276b3e-a6b1-4e8f-bd25-997016008f3b)
![Image](https://github.com/user-attachments/assets/41ce8c20-8d67-46f5-b70b-a4f54dfc7be7)
![Image](https://github.com/user-attachments/assets/4e9c76bd-93c2-4319-a692-8f5b5afee587)
![Image](https://github.com/user-attachments/assets/44ed3edf-7634-4d6c-886e-2bdad5355df4)
![Image](https://github.com/user-attachments/assets/4aa07fd7-5a12-4f25-8c53-ffd6bd032581)
![Image](https://github.com/user-attachments/assets/7a96e3fb-6dac-4280-8be8-659dbb1481e3)
![Image](https://github.com/user-attachments/assets/1eda183f-e020-4ced-8aeb-c5e9f016ec90)
![Image](https://github.com/user-attachments/assets/21016e64-83b5-48ee-a694-70312c3eeabb)
 ![Image](https://github.com/user-attachments/assets/35af8aba-02f0-4741-be25-42248e44cfd6)
![Image](https://github.com/user-attachments/assets/a0c70a96-057c-4ea0-bf41-f607c7755e38)
![Image](https://github.com/user-attachments/assets/74bf1de0-40df-459a-a155-a572aecbccf7)
![Image](https://github.com/user-attachments/assets/78d5c5cc-4498-4ad5-bb5b-1147d3ebf0e1)
![Image](https://github.com/user-attachments/assets/5256237e-1e89-4959-bb68-88212f51d3bf)
![Image](https://github.com/user-attachments/assets/d3d4700d-66ab-410e-9d66-fb6430ad4e4e)
![Image](https://github.com/user-attachments/assets/de9b54c9-356c-458d-b437-5e2916966dc8)
![Image](https://github.com/user-attachments/assets/e9150ddc-4b57-41e1-8885-f7a2e898bd18)
![Image](https://github.com/user-attachments/assets/6b2f448a-ca23-412f-b7c3-9905e64f6e31)
![Image](https://github.com/user-attachments/assets/e7b1e281-9487-47d9-9afa-f689f39bda3a)

</details>
